import type { ExerciseSeed } from './exercisesLibrary.seed';

type CommonExerciseInput = {
  name: string;
  freeDbId: string;
  bodyPart: string;
  targetMuscle: string;
  secondaryMuscles?: string[];
  equipment: string;
  aliases?: string[];
  movementPattern?: string;
};

const commonInstructions = [
  'Ajuste carga, banco ou máquina para manter amplitude confortável e controle total.',
  'Execute a fase principal sem impulso, mantendo respiração e postura estáveis.',
  'Retorne de forma controlada antes da próxima repetição.',
];

const commonTips = [
  'Priorize técnica consistente antes de aumentar carga.',
  'Interrompa se houver dor articular aguda ou perda clara de controle.',
];

function aliasTags(input: CommonExerciseInput): string[] {
  return [
    'academia',
    input.bodyPart,
    input.equipment,
    input.movementPattern ?? 'força',
    input.name,
    ...(input.aliases ?? []),
  ].map((tag) => tag.toLowerCase());
}

function makeExercise(input: CommonExerciseInput): ExerciseSeed {
  return {
    source: 'metacore',
    name: input.name,
    freeDbId: input.freeDbId,
    bodyPart: input.bodyPart,
    targetMuscle: input.targetMuscle,
    secondaryMuscles: input.secondaryMuscles ?? [],
    equipment: input.equipment,
    tags: aliasTags(input),
    instructions: commonInstructions,
    tips: commonTips,
  };
}

/**
 * Aliases PT-BR para exercícios que já existem no seed principal.
 * Evita duplicar movimentos como "Supino Reto" vs "Supino reto com barra",
 * mas permite que busca, builder, IA e fichas encontrem os termos clássicos.
 */
export const COMMON_GYM_EXERCISE_ALIASES: Record<string, string[]> = {
  'Supino Reto': ['Supino reto com barra'],
  'Supino Reto com Halteres': ['Supino reto com halteres'],
  'Supino Inclinado com Barra': ['Supino inclinado com barra'],
  'Supino Inclinado com Halteres': ['Supino inclinado com halteres'],
  'Supino Declinado com Halteres': ['Supino declinado com halteres'],
  'Crucifixo com Halteres': ['Crucifixo reto com halteres'],
  'Peck Deck (Máquina)': ['Crucifixo na máquina', 'Peck deck'],
  'Crossover no Cabo': ['Crossover alto', 'Crossover baixo'],
  'Flexão de Braço': ['Flexão de braço'],
  'Flexão Inclinada (Declinada)': ['Flexão inclinada', 'Flexão declinada'],
  'Pullover com Haltere': ['Pullover com halter'],

  'Puxada Frente (Lat Pulldown)': ['Puxada frontal aberta'],
  'Puxada na Polia Alta (Close Grip)': ['Puxada frontal fechada'],
  'Barra Fixa': ['Barra fixa pronada'],
  'Remada Curvada com Barra': ['Remada curvada com barra'],
  'Remada Unilateral com Haltere': ['Remada unilateral com halter'],
  'Remada Baixa no Cabo': ['Remada baixa no cabo'],
  'Remada T-Bar': ['Remada cavalinho'],
  'Remada Sentada no Cabo': ['Remada máquina'],
  'Levantamento Terra': ['Levantamento terra'],
  'Stiff (Romanian Deadlift)': ['Terra romeno', 'Stiff com barra'],
  'Hiperextensão Lombar': ['Hiperextensão lombar'],

  'Desenvolvimento com Barra (Press Militar)': ['Desenvolvimento militar com barra'],
  'Desenvolvimento com Halteres': ['Desenvolvimento com halteres'],
  'Arnold Press': ['Desenvolvimento Arnold'],
  'Elevação Lateral': ['Elevação lateral com halteres'],
  'Elevação Frontal': ['Elevação frontal com barra'],
  'Elevação Frontal com Halteres': ['Elevação frontal com halteres'],
  'Crucifixo Inverso (Elevação Posterior)': ['Elevação posterior com halteres', 'Crucifixo inverso'],
  'Face Pull no Cabo': ['Face pull'],
  'Encolhimento de Ombros com Halteres': ['Encolhimento com halteres'],
  'Remada Alta no Cabo': ['Remada alta'],

  'Rosca Direta com Barra': ['Rosca direta com barra', 'Rosca 21'],
  'Rosca Alternada com Halteres': ['Rosca alternada com halteres'],
  'Rosca Martelo': ['Rosca martelo'],
  'Rosca Concentrada': ['Rosca concentrada'],
  'Rosca Scott (Preacher Curl)': ['Rosca Scott com barra'],
  'Rosca Inclinada com Halteres': ['Rosca inclinada com halteres'],
  'Rosca 21 com Barra': ['Rosca 21'],

  'Tríceps Testa (Skull Crusher)': ['Tríceps testa com barra', 'Tríceps testa com barra reta'],
  'Tríceps Francês com Haltere': ['Tríceps francês com halter'],
  'Extensão de Tríceps com Haltere Unilateral': ['Tríceps francês unilateral', 'Tríceps francês unilateral com halter'],
  'Tríceps Corda (Pushdown)': ['Tríceps corda na polia', 'Tríceps corda na polia alta'],
  'Tríceps Pulley (Pushdown)': ['Tríceps barra reta na polia'],
  'Tríceps Coice com Haltere': ['Tríceps coice com halter'],
  'Fundinho (Bench Dip)': ['Tríceps banco'],
  'Dip em Barras Paralelas': ['Paralelas', 'Paralelas para tríceps'],
  'Flexão de Braço Fechada': ['Flexão fechada'],

  'Agachamento Livre': ['Agachamento livre'],
  'Agachamento Frontal': ['Agachamento frontal'],
  'Agachamento com Haltere (Goblet)': ['Agachamento goblet', 'Kettlebell goblet squat'],
  'Agachamento Sumô': ['Agachamento sumô'],
  'Hack Squat na Máquina': ['Hack squat'],
  'Leg Press 45°': ['Leg press 45'],
  'Cadeira Extensora': ['Cadeira extensora'],
  'Afundo (Lunge)': ['Afundo'],
  'Afundo com Barra': ['Avanço com barra'],
  'Afundo Reverso': ['Avanço com halteres'],
  'Agachamento Búlgaro': ['Afundo búlgaro'],
  'Stepup no Banco': ['Step-up no banco'],

  'Mesa Flexora (Leg Curl Deitado)': ['Mesa flexora'],
  'Good Morning': ['Good morning'],
  'Nordic Curl (Curl Nórdico)': ['Nordic curl'],
  'Elevação Pélvica (Hip Thrust)': ['Elevação pélvica com barra', 'Hip thrust'],
  'Ponte de Glúteo': ['Ponte de glúteos'],
  'Glúteo no Cabo (Kickback)': ['Glúteo na polia', 'Coice na polia'],
  'Glúteo 4 Apoios (Donkey Kick)': ['Coice com caneleira'],
  'Abdução de Quadril na Máquina': ['Abdução de quadril máquina'],
  'Abdução com Elástico (Monster Walk)': ['Abdução com elástico'],

  'Panturrilha em Pé (Calf Raise)': ['Panturrilha em pé'],
  'Prancha': ['Prancha frontal'],
  'Prancha Lateral': ['Prancha lateral'],
  'Prancha com Toque no Ombro': ['Prancha com toque no ombro'],
  'Dead Bug': ['Dead bug'],
  'Hollow Body Hold': ['Hollow hold'],
  'Mountain Climber': ['Mountain climber'],
  'Twist Russo': ['Russian twist'],
  'Elevação de Pernas Suspensa': ['Elevação de pernas', 'Elevação de joelhos na paralela'],
  'Crunch Abdominal': ['Abdominal supra', 'Crunch'],
  'Abdominal Infra (Elevação de Pernas)': ['Abdominal infra'],
  'Abdominal Bicicleta': ['Abdominal bicicleta'],
  'Crunch com Cabo': ['Abdominal na polia'],

  'Esteira (HIIT)': ['Esteira inclinada'],
  'Corrida na Esteira': ['Corrida na esteira', 'Sprints'],
  'Bicicleta Ergométrica': ['Bicicleta ergométrica', 'Bike spinning'],
  'Elíptico': ['Elíptico'],
  'Remo Ergométrico': ['Remo ergômetro'],
  'Pular Corda': ['Pular corda'],
  'Polichinelo (Jumping Jack)': ['Polichinelo'],
  'Burpee': ['Burpee'],
  'Corrida Elevada no Lugar': ['Corrida estacionária'],
  'Kettlebell Swing': ['Kettlebell swing'],
  'Box Jump': ['Box jump'],
  'Bear Crawl': ['Bear crawl'],
};

export const COMMON_GYM_EXERCISES_SEED: ExerciseSeed[] = [
  makeExercise({
    name: 'Supino Declinado com Barra',
    freeDbId: 'Decline_Barbell_Bench_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Tríceps braquial', 'Deltoide anterior'],
    equipment: 'barra',
    aliases: ['Supino declinado com barra'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Chest Press Máquina',
    freeDbId: 'Machine_Bench_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Tríceps braquial', 'Deltoide anterior'],
    equipment: 'máquina',
    aliases: ['Supino máquina', 'Chest press máquina'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Crucifixo Inclinado com Halteres',
    freeDbId: 'Incline_Dumbbell_Flyes',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (cabeça clavicular)',
    secondaryMuscles: ['Deltoide anterior'],
    equipment: 'halteres',
    aliases: ['Crucifixo inclinado com halteres'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Pullover na Polia',
    freeDbId: 'Rope_Straight-Arm_Pulldown',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior e grande dorsal',
    secondaryMuscles: ['Serrátil anterior', 'Core'],
    equipment: 'cabo',
    aliases: ['Pullover na polia', 'pulldown braços retos'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Puxada Supinada',
    freeDbId: 'Underhand_Cable_Pulldowns',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps braquial', 'Braquial'],
    equipment: 'cabo',
    aliases: ['Puxada supinada'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Puxada Neutra',
    freeDbId: 'V-Bar_Pulldown',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps braquial', 'Romboides'],
    equipment: 'cabo',
    aliases: ['Puxada neutra'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Barra Fixa Supinada',
    freeDbId: 'Chin-Up',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps braquial', 'Braquial'],
    equipment: 'peso_corporal',
    aliases: ['Barra fixa supinada'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Barra Fixa Assistida',
    freeDbId: 'Band_Assisted_Pull-Up',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps braquial', 'Romboides'],
    equipment: 'elástico',
    aliases: ['Barra fixa assistida'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Remada Articulada',
    freeDbId: 'Seated_Cable_Rows',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Romboides', 'Trapézio médio', 'Bíceps braquial'],
    equipment: 'máquina',
    aliases: ['Remada articulada', 'Remada máquina'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Remada Invertida',
    freeDbId: 'Bodyweight_Mid_Row',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Romboides', 'Bíceps braquial', 'Core'],
    equipment: 'peso_corporal',
    aliases: ['Remada invertida'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Pulldown com Braços Retos',
    freeDbId: 'Straight-Arm_Pulldown',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Redondo maior', 'Core'],
    equipment: 'cabo',
    aliases: ['Pulldown com braços retos'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Desenvolvimento na Máquina',
    freeDbId: 'Machine_Shoulder_Military_Press',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide anterior',
    secondaryMuscles: ['Deltoide lateral', 'Tríceps braquial'],
    equipment: 'máquina',
    aliases: ['Desenvolvimento na máquina', 'Shoulder press máquina'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Elevação Lateral na Polia',
    freeDbId: 'Standing_Low-Pulley_Deltoid_Raise',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide lateral',
    secondaryMuscles: ['Trapézio superior'],
    equipment: 'cabo',
    aliases: ['Elevação lateral na polia'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Elevação Lateral na Máquina',
    freeDbId: 'Calf-Machine_Shoulder_Shrug',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide lateral',
    secondaryMuscles: ['Trapézio superior'],
    equipment: 'máquina',
    aliases: ['Elevação lateral na máquina'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Encolhimento com Barra',
    freeDbId: 'Barbell_Shrug',
    bodyPart: 'ombro',
    targetMuscle: 'Trapézio superior',
    secondaryMuscles: ['Levantador da escápula'],
    equipment: 'barra',
    aliases: ['Encolhimento com barra'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Direta com Barra W',
    freeDbId: 'Close-Grip_EZ_Bar_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial', 'Braquiorradial'],
    equipment: 'barra w',
    aliases: ['Rosca direta com barra W'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Direta na Polia',
    freeDbId: 'Standing_Biceps_Cable_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'cabo',
    aliases: ['Rosca direta na polia'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Simultânea com Halteres',
    freeDbId: 'Dumbbell_Bicep_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'halteres',
    aliases: ['Rosca simultânea com halteres'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Martelo na Corda',
    freeDbId: 'Cable_Hammer_Curls_-_Rope_Attachment',
    bodyPart: 'bíceps',
    targetMuscle: 'Braquiorradial',
    secondaryMuscles: ['Bíceps braquial', 'Braquial'],
    equipment: 'cabo',
    aliases: ['Rosca martelo na corda'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Scott com Halter',
    freeDbId: 'One_Arm_Dumbbell_Preacher_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'halteres',
    aliases: ['Rosca Scott com halter'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Scott Máquina',
    freeDbId: 'Machine_Preacher_Curls',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'máquina',
    aliases: ['Rosca Scott máquina'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Spider',
    freeDbId: 'Spider_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'barra',
    aliases: ['Rosca spider'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Rosca Inversa',
    freeDbId: 'Standing_Dumbbell_Reverse_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Braquiorradial',
    secondaryMuscles: ['Bíceps braquial', 'Extensores do antebraço'],
    equipment: 'halteres',
    aliases: ['Rosca inversa'],
    movementPattern: 'puxar',
  }),
  makeExercise({
    name: 'Tríceps Testa com Halteres',
    freeDbId: 'Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Deltoide posterior'],
    equipment: 'halteres',
    aliases: ['Tríceps testa com halteres'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Tríceps Barra V na Polia',
    freeDbId: 'Triceps_Pushdown_-_V-Bar_Attachment',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'cabo',
    aliases: ['Tríceps barra V na polia'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Tríceps Coice na Polia',
    freeDbId: 'Standing_Low-Pulley_One-Arm_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Deltoide posterior'],
    equipment: 'cabo',
    aliases: ['Tríceps coice na polia'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Paralelas Assistidas',
    freeDbId: 'Dip_Machine',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral maior', 'Deltoide anterior'],
    equipment: 'máquina',
    aliases: ['Paralelas assistidas'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Supino Fechado',
    freeDbId: 'Close-Grip_Barbell_Bench_Press',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral maior', 'Deltoide anterior'],
    equipment: 'barra',
    aliases: ['Supino fechado'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Extensão de Tríceps Acima da Cabeça na Polia',
    freeDbId: 'Cable_Rope_Overhead_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'cabo',
    aliases: [
      'Extensão de tríceps acima da cabeça na polia',
      'Tríceps francês na corda',
      'Tríceps francês na corda na polia alta',
      'Tríceps francês na polia alta',
    ],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Agachamento no Smith',
    freeDbId: 'Smith_Machine_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Adutores'],
    equipment: 'smith',
    aliases: ['Agachamento no Smith'],
    movementPattern: 'agachar',
  }),
  makeExercise({
    name: 'Leg Press Horizontal',
    freeDbId: 'Leg_Press',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais'],
    equipment: 'máquina',
    aliases: ['Leg press horizontal'],
    movementPattern: 'agachar',
  }),
  makeExercise({
    name: 'Passada Caminhando',
    freeDbId: 'Barbell_Walking_Lunge',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais'],
    equipment: 'barra',
    aliases: ['Passada caminhando'],
    movementPattern: 'agachar',
  }),
  makeExercise({
    name: 'Sissy Squat',
    freeDbId: 'Weighted_Sissy_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Core'],
    equipment: 'peso_corporal',
    aliases: ['Sissy squat'],
    movementPattern: 'agachar',
  }),
  makeExercise({
    name: 'Cadeira Flexora',
    freeDbId: 'Seated_Leg_Curl',
    bodyPart: 'perna',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: ['Panturrilha'],
    equipment: 'máquina',
    aliases: ['Cadeira flexora'],
    movementPattern: 'flexão de joelho',
  }),
  makeExercise({
    name: 'Flexora em Pé',
    freeDbId: 'Standing_Leg_Curl',
    bodyPart: 'perna',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: ['Panturrilha'],
    equipment: 'máquina',
    aliases: ['Flexora em pé', 'Flexora unilateral'],
    movementPattern: 'flexão de joelho',
  }),
  makeExercise({
    name: 'Stiff com Halteres',
    freeDbId: 'Romanian_Deadlift',
    bodyPart: 'perna',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: ['Glúteo máximo', 'Eretores da espinha'],
    equipment: 'halteres',
    aliases: ['Stiff com halteres'],
    movementPattern: 'dobradiça de quadril',
  }),
  makeExercise({
    name: 'Elevação Pélvica Máquina',
    freeDbId: 'Smith_Machine_Hip_Raise',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais'],
    equipment: 'máquina',
    aliases: ['Elevação pélvica máquina'],
    movementPattern: 'extensão de quadril',
  }),
  makeExercise({
    name: 'Glúteo na Máquina',
    freeDbId: 'Glute_Kickback',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais'],
    equipment: 'máquina',
    aliases: ['Glúteo na máquina'],
    movementPattern: 'extensão de quadril',
  }),
  makeExercise({
    name: 'Abdução na Polia',
    freeDbId: 'Thigh_Adductor',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo médio',
    secondaryMuscles: ['Tensor da fáscia lata'],
    equipment: 'cabo',
    aliases: ['Abdução na polia'],
    movementPattern: 'abdução',
  }),
  makeExercise({
    name: 'Frog Pump',
    freeDbId: 'Frog_Sit-Ups',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Adutores'],
    equipment: 'peso_corporal',
    aliases: ['Frog pump'],
    movementPattern: 'extensão de quadril',
  }),
  makeExercise({
    name: 'Panturrilha Sentado',
    freeDbId: 'Seated_Calf_Raise',
    bodyPart: 'panturrilha',
    targetMuscle: 'Sóleo',
    secondaryMuscles: ['Gastrocnêmio'],
    equipment: 'máquina',
    aliases: ['Panturrilha sentado'],
    movementPattern: 'flexão plantar',
  }),
  makeExercise({
    name: 'Panturrilha no Leg Press',
    freeDbId: 'Calf_Press_On_The_Leg_Press_Machine',
    bodyPart: 'panturrilha',
    targetMuscle: 'Gastrocnêmio',
    secondaryMuscles: ['Sóleo'],
    equipment: 'máquina',
    aliases: ['Panturrilha no leg press'],
    movementPattern: 'flexão plantar',
  }),
  makeExercise({
    name: 'Panturrilha Unilateral',
    freeDbId: 'Calf_Raise_On_A_Dumbbell',
    bodyPart: 'panturrilha',
    targetMuscle: 'Gastrocnêmio',
    secondaryMuscles: ['Sóleo'],
    equipment: 'halteres',
    aliases: ['Panturrilha unilateral', 'Elevação de panturrilha no degrau'],
    movementPattern: 'flexão plantar',
  }),
  makeExercise({
    name: 'Panturrilha no Smith',
    freeDbId: 'Smith_Machine_Calf_Raise',
    bodyPart: 'panturrilha',
    targetMuscle: 'Gastrocnêmio',
    secondaryMuscles: ['Sóleo'],
    equipment: 'smith',
    aliases: ['Panturrilha no Smith'],
    movementPattern: 'flexão plantar',
  }),
  makeExercise({
    name: 'Panturrilha com Halteres',
    freeDbId: 'Standing_Dumbbell_Calf_Raise',
    bodyPart: 'panturrilha',
    targetMuscle: 'Gastrocnêmio',
    secondaryMuscles: ['Sóleo'],
    equipment: 'halteres',
    aliases: ['Panturrilha com halteres'],
    movementPattern: 'flexão plantar',
  }),
  makeExercise({
    name: 'Abdominal Máquina',
    freeDbId: 'Ab_Crunch_Machine',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Oblíquos'],
    equipment: 'máquina',
    aliases: ['Abdominal máquina'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Abdominal Completo',
    freeDbId: 'Sit-Up',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Flexores do quadril'],
    equipment: 'peso_corporal',
    aliases: ['Abdominal completo'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Crunch na Bola',
    freeDbId: 'Crunch_-_Legs_On_Exercise_Ball',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Oblíquos'],
    equipment: 'bola',
    aliases: ['Crunch na bola'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Abdominal Remador',
    freeDbId: '3_4_Sit-Up',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Flexores do quadril'],
    equipment: 'peso_corporal',
    aliases: ['Abdominal remador'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Abdominal Canivete',
    freeDbId: 'Jackknife_Sit-Up',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Flexores do quadril'],
    equipment: 'peso_corporal',
    aliases: ['Abdominal canivete'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Bird Dog',
    freeDbId: 'Superman',
    bodyPart: 'abdômen',
    targetMuscle: 'Core profundo',
    secondaryMuscles: ['Glúteo máximo', 'Eretores da espinha'],
    equipment: 'peso_corporal',
    aliases: ['Bird dog'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Pallof Press',
    freeDbId: 'Pallof_Press',
    bodyPart: 'abdômen',
    targetMuscle: 'Core anti-rotação',
    secondaryMuscles: ['Oblíquos', 'Glúteo médio'],
    equipment: 'cabo',
    aliases: ['Pallof press'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Ab Wheel',
    freeDbId: 'Ab_Roller',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Serrátil anterior', 'Grande dorsal'],
    equipment: 'roda abdominal',
    aliases: ['Ab wheel'],
    movementPattern: 'core',
  }),
  makeExercise({
    name: 'Caminhada na Esteira',
    freeDbId: 'Walking_Treadmill',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiorrespiratório',
    secondaryMuscles: ['Panturrilhas', 'Quadríceps'],
    equipment: 'esteira',
    aliases: ['Caminhada na esteira'],
    movementPattern: 'cardio',
  }),
  makeExercise({
    name: 'Escada Ergométrica',
    freeDbId: 'Stairmaster',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiorrespiratório',
    secondaryMuscles: ['Glúteo máximo', 'Quadríceps', 'Panturrilhas'],
    equipment: 'máquina',
    aliases: ['Escada ergométrica'],
    movementPattern: 'cardio',
  }),
  makeExercise({
    name: 'Kettlebell Deadlift',
    freeDbId: 'Kettlebell_Dead_Clean',
    bodyPart: 'perna',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais', 'Eretores da espinha'],
    equipment: 'kettlebell',
    aliases: ['Kettlebell deadlift'],
    movementPattern: 'dobradiça de quadril',
  }),
  makeExercise({
    name: 'Battle Rope',
    freeDbId: 'Battling_Ropes',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiorrespiratório',
    secondaryMuscles: ['Ombros', 'Core'],
    equipment: 'corda naval',
    aliases: ['Battle rope'],
    movementPattern: 'cardio',
  }),
  makeExercise({
    name: 'Slam Ball',
    freeDbId: 'Overhead_Slam',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiorrespiratório',
    secondaryMuscles: ['Core', 'Ombros', 'Grande dorsal'],
    equipment: 'medicine ball',
    aliases: ['Slam ball'],
    movementPattern: 'potência',
  }),
  makeExercise({
    name: 'Farmer Walk',
    freeDbId: 'Farmers_Walk',
    bodyPart: 'funcional',
    targetMuscle: 'Core e pegada',
    secondaryMuscles: ['Trapézio', 'Glúteo máximo', 'Panturrilhas'],
    equipment: 'halteres',
    aliases: ['Farmer walk'],
    movementPattern: 'carregada',
  }),
  makeExercise({
    name: 'Supino Inclinado na Máquina',
    freeDbId: 'Smith_Machine_Incline_Bench_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (cabeça clavicular)',
    secondaryMuscles: ['Deltoide anterior', 'Tríceps braquial'],
    equipment: 'máquina',
    aliases: ['Supino inclinado máquina', 'Incline chest press'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Crucifixo Inclinado na Máquina',
    freeDbId: 'Incline_Cable_Flye',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (cabeça clavicular)',
    secondaryMuscles: ['Deltoide anterior'],
    equipment: 'cabo',
    aliases: ['Crucifixo inclinado máquina', 'Incline cable fly'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Crossover Polia Média',
    freeDbId: 'Cable_Crossover',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (porção esternal)',
    secondaryMuscles: ['Deltoide anterior', 'Serrátil anterior'],
    equipment: 'cabo',
    aliases: ['Crossover polia média', 'Crossover meio'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Leg Press 80°',
    freeDbId: 'Leg_Press',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais'],
    equipment: 'máquina',
    aliases: ['Leg press 80', 'Leg 80', 'Leg press vertical'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Supino Reto na Máquina',
    freeDbId: 'Machine_Bench_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Tríceps braquial', 'Deltoide anterior'],
    equipment: 'máquina',
    aliases: ['Supino reto máquina', 'Supino reto na máquina', 'Chest press reto'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Crossover Polia Alta',
    freeDbId: 'Cable_Crossover',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (porção inferior)',
    secondaryMuscles: ['Deltoide anterior', 'Serrátil anterior'],
    equipment: 'cabo',
    aliases: ['Crossover polia alta', 'Crossover alto', 'High cable crossover'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Crossover Polia Baixa',
    freeDbId: 'Low_Cable_Crossover',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (porção clavicular)',
    secondaryMuscles: ['Deltoide anterior'],
    equipment: 'cabo',
    aliases: ['Crossover polia baixa', 'Crossover baixo', 'Low cable crossover'],
    movementPattern: 'isolamento',
  }),
  // ── Tríceps — complementar (rodada 26/05/2026) ─────────────────────
  makeExercise({
    name: 'Tríceps Francês Unilateral na Polia',
    freeDbId: 'Cable_One_Arm_Tricep_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'cabo',
    aliases: ['Tríceps francês unilateral na polia', 'Francês unilateral cabo'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Tríceps Francês na Polia Baixa',
    freeDbId: 'Sled_Overhead_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça longa)',
    secondaryMuscles: [],
    equipment: 'cabo',
    aliases: ['Tríceps francês na polia baixa', 'Overhead triceps polia baixa'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Tríceps Unilateral na Polia',
    freeDbId: 'Cable_One_Arm_Tricep_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'cabo',
    aliases: ['Tríceps unilateral na polia', 'Pushdown unilateral'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Tríceps Inverso na Polia',
    freeDbId: 'Reverse_Grip_Triceps_Pushdown',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça medial)',
    secondaryMuscles: [],
    equipment: 'cabo',
    aliases: ['Tríceps inverso na polia', 'Reverse grip pushdown', 'Pushdown supinado'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Tríceps Testa com Barra W',
    freeDbId: 'EZ-Bar_Skullcrusher',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'barra w',
    aliases: ['Tríceps testa com barra W', 'Skull crusher EZ', 'Skull crusher barra W'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Tríceps Francês com Barra W Sentado',
    freeDbId: 'Seated_Triceps_Press',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça longa)',
    secondaryMuscles: [],
    equipment: 'barra w',
    aliases: ['Tríceps francês com barra W sentado', 'Francês EZ sentado', 'Seated overhead EZ'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Tríceps Francês com Barra W em Pé',
    freeDbId: 'Standing_Overhead_Barbell_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça longa)',
    secondaryMuscles: [],
    equipment: 'barra w',
    aliases: ['Tríceps francês com barra W em pé', 'Francês EZ em pé', 'Standing overhead EZ'],
    movementPattern: 'isolamento',
  }),
  makeExercise({
    name: 'Mergulho na Máquina',
    freeDbId: 'Dip_Machine',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral inferior', 'Deltoide anterior'],
    equipment: 'máquina',
    aliases: ['Mergulho na máquina', 'Dip máquina', 'Dip machine'],
    movementPattern: 'empurrar',
  }),
  makeExercise({
    name: 'Tríceps Máquina',
    freeDbId: 'Machine_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'máquina',
    aliases: ['Tríceps máquina', 'Triceps extension machine', 'Extensão de tríceps na máquina'],
    movementPattern: 'isolamento',
  }),
];
