/**
 * Biblioteca proprietária MetaCore de exercícios.
 * Seed curado com ~180 exercícios — expansível para 500+.
 * Schema inspirado no ExerciseDB v2.
 *
 * Campos:
 *  - externalId: identificador externo opcional (null = MetaCore original)
 *  - source: 'metacore' (todos neste seed)
 *  - name: nome PT-BR
 *  - bodyPart: grupo principal
 *  - targetMuscle / secondaryMuscles: músculos
 *  - equipment: equipamento (barra, halteres, máquina, cabo, peso_corporal, etc.)
 *  - tags: termos de busca e filtragem
 *  - instructions / tips: passo a passo e dicas (PT-BR)
 *  - freeDbId: ID no free-exercise-db (yuhonas/free-exercise-db) para GIF automático
 *  - youtubeId: ID YouTube opcional — curador admin preenche via PATCH /api/exercises/:id
 *  - imageUrl / videoUrl: override manual quando freeDbId/youtubeId não cobrem
 *
 * GIF URL gerada automaticamente:
 *   https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{freeDbId}/0.jpg
 */

export type ExerciseSeed = {
  externalId?: string | null;
  source: 'metacore';
  name: string;
  bodyPart: string;
  targetMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  tags: string[];
  instructions: string[];
  tips: string[];
  /** ID no repositório free-exercise-db para resolução automática de GIF/imagem */
  freeDbId?: string | null;
  /** ID do YouTube — curadoria manual; inserido em exercise_media como media_type='youtube' */
  youtubeId?: string | null;
  imageUrl?: string | null;
  videoUrl?: string | null;
};

export const EXERCISES_SEED: ExerciseSeed[] = [
  // ─── PEITO ───────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Supino Reto',
    freeDbId: 'Barbell_Bench_Press_-_Medium_Grip',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Tríceps braquial', 'Deltoide anterior'],
    equipment: 'barra',
    tags: ['academia', 'hipertrofia', 'força'],
    instructions: [
      'Deite no banco reto, pés apoiados no chão.',
      'Segure a barra com pegada pronada, mãos levemente mais largas que os ombros.',
      'Desça a barra de forma controlada até o peito.',
      'Empurre a barra para cima até estender os cotovelos.',
    ],
    tips: [
      'Mantenha os ombros retraídos e deprimidos durante todo o movimento.',
      'Evite arquear excessivamente a lombar.',
      'Desça a barra até o esterno, não o pescoço.',
    ],
  },
  {
    source: 'metacore',
    name: 'Supino Inclinado com Halteres',
    freeDbId: 'Incline_Dumbbell_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior (cabeça clavicular)',
    secondaryMuscles: ['Tríceps braquial', 'Deltoide anterior'],
    equipment: 'halteres',
    tags: ['academia', 'hipertrofia'],
    instructions: [
      'Ajuste o banco a 30–45° de inclinação.',
      'Sente-se com um halter em cada mão apoiado nas coxas.',
      'Deite empurrando os halteres para a posição de trabalho.',
      'Desça os halteres até a linha dos mamilos com cotovelos a 75°.',
      'Empurre de volta até os halteres quase se tocarem no topo.',
    ],
    tips: [
      'Ângulo de 30° ativa mais fibras claviculares sem sobrecarregar o ombro.',
      'Não trave completamente os cotovelos no topo.',
    ],
  },
  {
    source: 'metacore',
    name: 'Crucifixo com Halteres',
    freeDbId: 'Dumbbell_Flyes',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Bíceps braquial (cabeça curta)', 'Deltoide anterior'],
    equipment: 'halteres',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'Deite no banco plano com um halter em cada mão.',
      'Estique os braços sobre o peito com cotovelos levemente dobrados.',
      'Abra os braços em arco, descendo os halteres até a altura do peito.',
      'Retorne ao ponto inicial contraindo o peitoral.',
    ],
    tips: [
      'Mantenha o leve ângulo do cotovelo constante — não mude no meio do movimento.',
      'Foque na contração do peitoral no topo.',
    ],
  },
  {
    source: 'metacore',
    name: 'Crossover no Cabo',
    freeDbId: 'Cable_Crossover',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Deltoide anterior'],
    equipment: 'cabo',
    tags: ['academia', 'isolamento', 'definição'],
    instructions: [
      'Posicione as polias na altura dos ombros ou acima.',
      'Segure a alça de cada lado e dê um passo à frente.',
      'Com leve inclinação para frente, cruze os braços à frente do corpo.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Varie a altura das polias para atingir diferentes porções do peitoral.',
      'Foque na fase excêntrica (retorno) para maximizar hipertrofia.',
    ],
  },
  {
    source: 'metacore',
    name: 'Flexão de Braço',
    freeDbId: 'Pushups',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Tríceps braquial', 'Deltoide anterior', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'funcional'],
    instructions: [
      'Posicione mãos levemente mais largas que os ombros, corpo reto.',
      'Desça o peito até quase tocar o chão.',
      'Empurre de volta à posição inicial.',
    ],
    tips: [
      'Mantenha o core contraído — não deixe o quadril cair.',
      'Varie a largura da pegada para atingir diferentes porções do peitoral.',
    ],
  },
  {
    source: 'metacore',
    name: 'Peck Deck (Máquina)',
    freeDbId: 'Butterfly',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Deltoide anterior'],
    equipment: 'máquina',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'Sente-se na máquina com costas apoiadas no encosto.',
      'Posicione os antebraços nas almofadas.',
      'Junte os braços à frente do corpo contraindo o peitoral.',
      'Retorne de forma controlada sem deixar as placas baterem.',
    ],
    tips: [
      'Boa opção para iniciantes e isolamento pré-exaustão.',
      'Controle a fase excêntrica em 2–3 segundos.',
    ],
  },
  // ─── COSTAS ──────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Puxada Frente (Lat Pulldown)',
    freeDbId: 'Wide-Grip_Lat_Pulldown',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps braquial', 'Redondo maior', 'Rombóide'],
    equipment: 'cabo',
    tags: ['academia', 'hipertrofia', 'força'],
    instructions: [
      'Sente-se na máquina e ajuste o joelheiro para prender as coxas.',
      'Segure a barra com pegada pronada, mãos mais largas que os ombros.',
      'Puxe a barra até o queixo, trazendo os cotovelos para baixo e para trás.',
      'Retorne de forma controlada até estender completamente os braços.',
    ],
    tips: [
      'Não use impulso do corpo — mantenha o tronco levemente inclinado.',
      'Foque em puxar com os cotovelos, não com as mãos.',
    ],
  },
  {
    source: 'metacore',
    name: 'Remada Curvada com Barra',
    freeDbId: 'Bent_Over_Barbell_Row',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Rombóide', 'Trapézio médio', 'Bíceps braquial', 'Eretores da espinha'],
    equipment: 'barra',
    tags: ['academia', 'hipertrofia', 'força'],
    instructions: [
      'Incline o tronco a 45°, barra nas mãos em pegada pronada.',
      'Puxe a barra em direção ao umbigo.',
      'Comprima as escápulas no final do movimento.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Mantenha a coluna neutra — não arredonde a lombar.',
      'O cotovelo deve passar levemente além das costas no pico.',
    ],
  },
  {
    source: 'metacore',
    name: 'Remada Unilateral com Haltere',
    freeDbId: 'Bent_Over_Two-Dumbbell_Row',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Rombóide', 'Trapézio', 'Bíceps braquial'],
    equipment: 'halteres',
    tags: ['academia', 'hipertrofia', 'unilateral'],
    instructions: [
      'Apoie um joelho e a mão no banco.',
      'Segure o halter com a mão oposta, braço estendido.',
      'Puxe o halter em direção ao quadril lateral, cotovelo para trás.',
      'Desça de forma controlada.',
    ],
    tips: [
      'Permita leve rotação do tronco para maior amplitude.',
      'Não deixe o ombro cair no ponto mais baixo.',
    ],
  },
  {
    source: 'metacore',
    name: 'Barra Fixa',
    freeDbId: 'Pullups',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps braquial', 'Braquial', 'Rombóide'],
    equipment: 'peso_corporal',
    tags: ['academia', 'casa', 'funcional', 'força'],
    instructions: [
      'Segure a barra com pegada pronada, mãos mais largas que os ombros.',
      'Pendure-se com os braços estendidos.',
      'Puxe o corpo até o queixo passar a barra.',
      'Desça de forma controlada.',
    ],
    tips: [
      'Escápulas retraídas antes de iniciar o movimento.',
      'Progrida com colete de carga conforme ficar fácil.',
    ],
  },
  {
    source: 'metacore',
    name: 'Remada Baixa no Cabo',
    freeDbId: 'Low_Pulley_Row_To_Neck',
    bodyPart: 'costas',
    targetMuscle: 'Rombóide',
    secondaryMuscles: ['Grande dorsal', 'Trapézio médio', 'Bíceps braquial'],
    equipment: 'cabo',
    tags: ['academia', 'hipertrofia'],
    instructions: [
      'Sente-se na máquina de remada, pés no apoio.',
      'Segure o triângulo ou barra curta.',
      'Puxe em direção ao abdômen comprimindo as escápulas.',
      'Retorne com controle, permitindo leve elongação das costas.',
    ],
    tips: [
      'Evite balançar o tronco para trás — use o core para estabilização.',
    ],
  },
  // ─── PERNA ───────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Agachamento Livre',
    freeDbId: 'Barbell_Full_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais', 'Eretores da espinha', 'Core'],
    equipment: 'barra',
    tags: ['academia', 'composto', 'força', 'hipertrofia'],
    instructions: [
      'Posicione a barra no trapézio baixo (high bar) ou médio.',
      'Pés na largura dos ombros, pontas levemente para fora.',
      'Desça controladamente até as coxas ficarem paralelas ao chão.',
      'Suba empurrando o chão, mantendo o joelho alinhado com o pé.',
    ],
    tips: [
      'Joelhos não devem colapsar para dentro.',
      'Mantenha o peito alto durante todo o movimento.',
      'Respire fundo antes de descer (manobra de Valsalva).',
    ],
  },
  {
    source: 'metacore',
    name: 'Leg Press 45°',
    freeDbId: 'Leg_Press',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais', 'Panturrilha'],
    equipment: 'máquina',
    tags: ['academia', 'hipertrofia'],
    instructions: [
      'Sente na plataforma com os pés na largura dos ombros na plataforma.',
      'Desça a plataforma até os joelhos formarem ≈ 90°.',
      'Empurre a plataforma de volta sem travar completamente os joelhos.',
    ],
    tips: [
      'Não deixe os joelhos colapsarem para dentro.',
      'Quanto mais alto os pés, maior ativação de glúteo/isquiotibiais.',
    ],
  },
  {
    source: 'metacore',
    name: 'Cadeira Extensora',
    freeDbId: 'Leg_Extensions',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: [],
    equipment: 'máquina',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'Sente na cadeira, tornozelos apoiados no rolo.',
      'Estenda os joelhos contraindo os quadríceps.',
      'Retorne de forma controlada sem bater o peso.',
    ],
    tips: [
      'Mantenha contração isométrica de 1–2s no pico.',
      'Cuidado com excesso de carga se houver histórico de joelho.',
    ],
  },
  {
    source: 'metacore',
    name: 'Mesa Flexora (Leg Curl Deitado)',
    freeDbId: 'Lying_Leg_Curls',
    bodyPart: 'perna',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: ['Panturrilha (gastrocnêmio)'],
    equipment: 'máquina',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'Deite na máquina, tornozelos sob o rolo.',
      'Contraia os isquiotibiais flexionando os joelhos.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Não levante o quadril para conseguir mais amplitude.',
      'Fase excêntrica lenta (3–4s) maximiza hipertrofia.',
    ],
  },
  {
    source: 'metacore',
    name: 'Stiff (Romanian Deadlift)',
    freeDbId: 'Romanian_Deadlift',
    bodyPart: 'perna',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: ['Glúteo máximo', 'Eretores da espinha'],
    equipment: 'barra',
    tags: ['academia', 'hipertrofia', 'força'],
    instructions: [
      'Segure a barra na frente das coxas, pés na largura dos quadris.',
      'Incline o tronco para frente empurrando o quadril para trás.',
      'Desça a barra ao longo das pernas até sentir alongamento nos isquiotibiais.',
      'Retorne empurrando o quadril para frente.',
    ],
    tips: [
      'Mantenha leve flexão nos joelhos (não é levantamento terra).',
      'Costas retas durante todo o movimento.',
    ],
  },
  {
    source: 'metacore',
    name: 'Afundo (Lunge)',
    freeDbId: 'Dumbbell_Lunges',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais'],
    equipment: 'halteres',
    tags: ['academia', 'casa', 'funcional', 'unilateral'],
    instructions: [
      'Em pé com halteres nas mãos, dê um passo à frente.',
      'Desça o joelho traseiro em direção ao chão.',
      'Volte à posição inicial empurrando pelo calcanhar do pé da frente.',
    ],
    tips: [
      'Joelho da frente não deve ultrapassar a ponta do pé.',
      'Mantenha o tronco ereto.',
    ],
  },
  {
    source: 'metacore',
    name: 'Panturrilha em Pé (Calf Raise)',
    freeDbId: 'Rocking_Standing_Calf_Raise',
    bodyPart: 'perna',
    targetMuscle: 'Gastrocnêmio',
    secondaryMuscles: ['Sóleo'],
    equipment: 'máquina',
    tags: ['academia', 'isolamento'],
    instructions: [
      'Posicione os ombros sob os apoios, pontas dos pés na plataforma.',
      'Suba nas pontas dos pés contraindo a panturrilha.',
      'Desça até sentir alongamento do calcanhar abaixo da plataforma.',
    ],
    tips: [
      'Amplitude total é essencial — panturrilha responde bem a volume e amplitude.',
      '3–4 séries de 15–25 reps funciona bem.',
    ],
  },
  // ─── GLÚTEO ───────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Elevação Pélvica (Hip Thrust)',
    freeDbId: 'Barbell_Hip_Thrust',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais', 'Core'],
    equipment: 'barra',
    tags: ['academia', 'hipertrofia', 'glúteo'],
    instructions: [
      'Apoie as escápulas em banco, barra sobre o colo com proteção.',
      'Pés no chão, joelhos a 90°.',
      'Empurre o quadril para cima contraindo glúteos.',
      'Desça controladamente.',
    ],
    tips: [
      'Mantenha queixo no peito para não estender a cervical.',
      'No topo, pernas e tronco formam linha reta — não hiperstenda a lombar.',
    ],
  },
  {
    source: 'metacore',
    name: 'Abdução de Quadril na Máquina',
    freeDbId: 'Thigh_Adductor',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo médio',
    secondaryMuscles: ['Glúteo mínimo', 'TFL'],
    equipment: 'máquina',
    tags: ['academia', 'isolamento', 'glúteo'],
    instructions: [
      'Sente na máquina com coxas apoiadas nas almofadas.',
      'Abra as pernas contra a resistência.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Adicione contração isométrica de 1s na abertura máxima.',
    ],
  },
  {
    source: 'metacore',
    name: 'Agachamento Sumô',
    freeDbId: 'Plie_Dumbbell_Squat',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Adutores', 'Quadríceps', 'Isquiotibiais'],
    equipment: 'halteres',
    tags: ['academia', 'casa', 'glúteo'],
    instructions: [
      'Pés mais largos que os ombros, pontas bem abertas.',
      'Segure um halter com ambas as mãos entre as pernas.',
      'Desça mantendo o tronco ereto.',
      'Suba empurrando pelos calcanhares.',
    ],
    tips: [
      'Joelhos seguem a direção das pontas dos pés.',
    ],
  },
  // ─── OMBRO ────────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Desenvolvimento com Halteres',
    freeDbId: 'Dumbbell_Shoulder_Press',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide medial',
    secondaryMuscles: ['Deltoide anterior', 'Tríceps braquial', 'Trapézio'],
    equipment: 'halteres',
    tags: ['academia', 'hipertrofia', 'força'],
    instructions: [
      'Sente no banco com encosto, halteres ao nível dos ombros.',
      'Empurre os halteres acima da cabeça até quase tocar.',
      'Desça controladamente até os cotovelos ficarem um pouco abaixo dos ombros.',
    ],
    tips: [
      'Não bloqueie totalmente os cotovelos no topo.',
      'Leve arco lombar natural — não exagere.',
    ],
  },
  {
    source: 'metacore',
    name: 'Elevação Lateral',
    freeDbId: 'Seated_Side_Lateral_Raise',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide medial',
    secondaryMuscles: ['Deltoide anterior', 'Trapézio'],
    equipment: 'halteres',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'Em pé, halteres ao lado do corpo.',
      'Eleve os braços lateralmente até a altura dos ombros.',
      'Desça controladamente.',
    ],
    tips: [
      'Cotovelos levemente dobrados durante o movimento.',
      'Fique com as mãos levemente abaixadas no pico (como despejar líquido) para maior ativação medial.',
    ],
  },
  {
    source: 'metacore',
    name: 'Elevação Frontal',
    freeDbId: 'Front_Raise_And_Pullover',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide anterior',
    secondaryMuscles: ['Peitoral (feixe clavicular)', 'Trapézio'],
    equipment: 'halteres',
    tags: ['academia', 'isolamento'],
    instructions: [
      'Em pé, halteres à frente das coxas.',
      'Eleve um ou ambos os braços à frente até a altura dos ombros.',
      'Desça de forma controlada.',
    ],
    tips: [
      'Evite balançar o corpo para ganhar impulso.',
    ],
  },
  {
    source: 'metacore',
    name: 'Crucifixo Inverso (Elevação Posterior)',
    freeDbId: 'Cable_Rear_Delt_Fly',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide posterior',
    secondaryMuscles: ['Rombóide', 'Trapézio médio'],
    equipment: 'halteres',
    tags: ['academia', 'isolamento', 'postura'],
    instructions: [
      'Incline o tronco a 45°, halteres nas mãos.',
      'Eleve os braços lateralmente em arco até a altura dos ombros.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Cotovelos levemente dobrados.',
      'Excelente para equilíbrio entre anterior e posterior do ombro.',
    ],
  },
  {
    source: 'metacore',
    name: 'Arnold Press',
    freeDbId: 'Arnold_Dumbbell_Press',
    bodyPart: 'ombro',
    targetMuscle: 'Deltoide (todos os feixes)',
    secondaryMuscles: ['Tríceps braquial', 'Trapézio'],
    equipment: 'halteres',
    tags: ['academia', 'hipertrofia'],
    instructions: [
      'Sente com halteres à frente, palmas para o corpo.',
      'Ao pressionar para cima, gire as palmas para fora.',
      'No topo, palmas para frente. Inverta na descida.',
    ],
    tips: [
      'Movimento de rotação ativa todos os três feixes do deltoide.',
    ],
  },
  // ─── BÍCEPS ───────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Rosca Direta com Barra',
    freeDbId: 'Barbell_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial', 'Braquiorradial'],
    equipment: 'barra',
    tags: ['academia', 'hipertrofia', 'força'],
    instructions: [
      'Em pé, barra em pegada supinada na largura dos ombros.',
      'Flexione os cotovelos trazendo a barra em direção aos ombros.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Cotovelos fixos ao lado do corpo.',
      'Evite balançar o tronco.',
    ],
  },
  {
    source: 'metacore',
    name: 'Rosca Alternada com Halteres',
    freeDbId: 'Dumbbell_Alternate_Bicep_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial', 'Braquiorradial'],
    equipment: 'halteres',
    tags: ['academia', 'casa', 'hipertrofia'],
    instructions: [
      'Em pé ou sentado, halter em cada mão.',
      'Flexione um cotovelo de cada vez, girando a palma para cima.',
      'Retorne e alterne os lados.',
    ],
    tips: [
      'Supinação máxima no pico da contração ativa mais fibras do bíceps.',
    ],
  },
  {
    source: 'metacore',
    name: 'Rosca Martelo',
    freeDbId: 'Hammer_Curls',
    bodyPart: 'bíceps',
    targetMuscle: 'Braquiorradial',
    secondaryMuscles: ['Bíceps braquial', 'Braquial'],
    equipment: 'halteres',
    tags: ['academia', 'hipertrofia'],
    instructions: [
      'Em pé, halteres em pegada neutra (polegar para cima).',
      'Flexione os cotovelos sem girar os pulsos.',
      'Retorne de forma controlada.',
    ],
    tips: [
      'Excelente para espessura do braço, diferente da rosca direta.',
    ],
  },
  {
    source: 'metacore',
    name: 'Rosca Scott (Preacher Curl)',
    freeDbId: 'Preacher_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial (cabeça curta)',
    secondaryMuscles: ['Braquial'],
    equipment: 'barra',
    tags: ['academia', 'isolamento'],
    instructions: [
      'Apoie os braços no banco Scott, barra em pegada supinada.',
      'Flexione os cotovelos trazendo a barra em direção ao rosto.',
      'Retorne sem estender completamente o cotovelo.',
    ],
    tips: [
      'Não deixe a barra cair de forma abrupta — cuidado com lesão.',
    ],
  },
  // ─── TRÍCEPS ──────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Tríceps Corda (Pushdown)',
    freeDbId: 'Triceps_Pushdown_-_Rope_Attachment',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'cabo',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'De pé na polia alta, segure a corda na largura dos ombros.',
      'Empurre a corda para baixo estendendo os cotovelos.',
      'Abra as duas pontas da corda no final para maior ativação.',
      'Retorne controladamente.',
    ],
    tips: [
      'Cotovelos fixos ao lado do corpo.',
    ],
  },
  {
    source: 'metacore',
    name: 'Tríceps Testa (Skull Crusher)',
    freeDbId: 'Decline_Close-Grip_Bench_To_Skull_Crusher',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'barra',
    tags: ['academia', 'hipertrofia'],
    instructions: [
      'Deite no banco plano, barra acima do peito.',
      'Flexione os cotovelos descendo a barra em direção à testa.',
      'Estenda de volta à posição inicial.',
    ],
    tips: [
      'Cotovelos apontados para o teto — não deixe abrir.',
      'Use barra EZ para reduzir stress no punho.',
    ],
  },
  {
    source: 'metacore',
    name: 'Tríceps Francês com Haltere',
    freeDbId: 'Overhead_Triceps',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça longa)',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'isolamento', 'hipertrofia'],
    instructions: [
      'Sentado, segure um halter com ambas as mãos acima da cabeça.',
      'Desça o halter atrás da cabeça flexionando os cotovelos.',
      'Estenda de volta ao topo.',
    ],
    tips: [
      'Ativa fortemente a cabeça longa do tríceps (maior volume).',
    ],
  },
  {
    source: 'metacore',
    name: 'Mergulho (Tríceps Dip)',
    freeDbId: 'Dips_-_Triceps_Version',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral menor', 'Deltoide anterior'],
    equipment: 'peso_corporal',
    tags: ['academia', 'casa', 'funcional'],
    instructions: [
      'Apoie as mãos em barras paralelas ou banco, corpo ereto.',
      'Desça flexionando os cotovelos até 90°.',
      'Empurre de volta à posição inicial.',
    ],
    tips: [
      'Tronco ereto = mais foco em tríceps; inclinado para frente = mais peitoral.',
    ],
  },
  // ─── ABDÔMEN ──────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Prancha Isométrica',
    freeDbId: 'Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Core (transverso abdominal)',
    secondaryMuscles: ['Reto abdominal', 'Oblíquos', 'Glúteo médio'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'funcional', 'estabilização'],
    instructions: [
      'Apoie-se nos antebraços e pontas dos pés, corpo reto.',
      'Contraia o abdômen e glúteos.',
      'Mantenha a posição pelo tempo determinado.',
    ],
    tips: [
      'Não deixe o quadril subir ou cair.',
      'Progrida em tempo: 30s → 45s → 60s → 90s.',
    ],
  },
  {
    source: 'metacore',
    name: 'Crunch Abdominal',
    freeDbId: 'Crunches',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: ['Oblíquos'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia'],
    instructions: [
      'Deite com joelhos dobrados, pés no chão.',
      'Mãos na nuca ou cruzadas no peito.',
      'Eleve o tronco contraindo o abdômen até os ombros saírem do chão.',
      'Retorne controladamente.',
    ],
    tips: [
      'Evite puxar o pescoço com as mãos.',
      'Enfatize a contração, não a amplitude.',
    ],
  },
  {
    source: 'metacore',
    name: 'Abdominal Infra (Elevação de Pernas)',
    freeDbId: 'Flat_Bench_Lying_Leg_Raise',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal inferior',
    secondaryMuscles: ['Flexores do quadril'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia'],
    instructions: [
      'Deite com as costas no chão, mãos ao lado do corpo.',
      'Eleve as pernas estendidas até 90°.',
      'Desça controladamente sem tocar o chão.',
    ],
    tips: [
      'Se a lombar sair do chão, flexione levemente os joelhos.',
    ],
  },
  {
    source: 'metacore',
    name: 'Oblíquo com Rotação',
    freeDbId: 'Oblique_Crunches',
    bodyPart: 'abdômen',
    targetMuscle: 'Oblíquo externo',
    secondaryMuscles: ['Oblíquo interno', 'Reto abdominal'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia'],
    instructions: [
      'Deite com joelhos dobrados.',
      'Eleve o tronco girando o cotovelo em direção ao joelho oposto.',
      'Alterne os lados.',
    ],
    tips: [
      'Rotação vem do tronco, não do pescoço.',
    ],
  },
  // ─── CARDIO / FUNCIONAL ────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Esteira (HIIT)',
    freeDbId: 'Running_Treadmill',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Quadríceps', 'Isquiotibiais', 'Panturrilha'],
    equipment: 'esteira',
    tags: ['academia', 'cardio', 'hiit', 'emagrecimento'],
    instructions: [
      'Aqueça 3 min em ritmo moderado.',
      'Alterne 30s de sprint intenso (85–95% FCmax) com 60s de caminhada.',
      'Repita 6–10 ciclos.',
      'Desacelere 3 min no final.',
    ],
    tips: [
      'Monitore a FC para garantir a intensidade correta nos sprints.',
    ],
  },
  {
    source: 'metacore',
    name: 'Burpee',
    freeDbId: 'Freehand_Jump_Squat',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Peitoral', 'Quadríceps', 'Core', 'Deltoide'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'hiit', 'funcional', 'emagrecimento'],
    instructions: [
      'Em pé, desça agachando e apoie as mãos no chão.',
      'Jogue os pés para trás, chegando em posição de flexão.',
      'Faça uma flexão (opcional).',
      'Traga os pés de volta ao agachamento e suba em salto com braços acima.',
    ],
    tips: [
      'Mantenha o abdômen contraído durante toda a sequência.',
    ],
  },
  {
    source: 'metacore',
    name: 'Mountain Climber',
    freeDbId: 'Mountain_Climbers',
    bodyPart: 'cardio',
    targetMuscle: 'Core',
    secondaryMuscles: ['Flexores do quadril', 'Deltoide', 'Peitoral'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'funcional', 'cardio'],
    instructions: [
      'Posição de prancha, braços estendidos.',
      'Traga um joelho em direção ao peito alternando os lados rapidamente.',
    ],
    tips: [
      'Quadril nivelado — não deixe oscilar para os lados.',
    ],
  },
  {
    source: 'metacore',
    name: 'Jumping Jacks',
    freeDbId: 'Freehand_Jump_Squat',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Glúteo médio', 'Deltoide'],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'cardio'],
    instructions: [
      'Em pé, braços ao lado do corpo.',
      'Salte abrindo pernas e levantando os braços acima da cabeça.',
      'Salte de volta à posição inicial.',
    ],
    tips: [
      'Ótimo exercício de aquecimento — 2-3 min despertam a FC.',
    ],
  },
  // ─── CASA ─────────────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Agachamento Livre (Peso Corporal)',
    freeDbId: 'Bodyweight_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'aquecimento'],
    instructions: [
      'Pés na largura dos ombros, pontas levemente abertas.',
      'Desça como se fosse sentar em uma cadeira.',
      'Suba empurrando pelos calcanhares.',
    ],
    tips: [
      'Braços à frente para equilíbrio.',
    ],
  },
  {
    source: 'metacore',
    name: 'Glúteo 4 Apoios (Donkey Kick)',
    freeDbId: 'Glute_Kickback',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'glúteo', 'isolamento'],
    instructions: [
      'Apoie-se em quatro apoios (mãos e joelhos).',
      'Chute uma perna para trás e para cima, contraindo o glúteo.',
      'Retorne sem tocar o joelho no chão e repita.',
    ],
    tips: [
      'Não gire o quadril — mantenha estável.',
    ],
  },
  {
    source: 'metacore',
    name: 'Flexão Diamante',
    freeDbId: 'Incline_Push-Up_Close-Grip',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral (feixe esternal)'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'funcional'],
    instructions: [
      'Posição de flexão com mãos juntas formando losango.',
      'Desça o peito em direção às mãos.',
      'Empurre de volta.',
    ],
    tips: [
      'Cotovelos colados ao corpo durante o movimento.',
    ],
  },

  // ─── PEITO (adicionais) ──────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Supino Inclinado com Barra',
    freeDbId: 'Barbell_Incline_Bench_Press_-_Medium_Grip',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral (feixe clavicular)',
    secondaryMuscles: ['Deltóide anterior', 'Tríceps'],
    equipment: 'barra',
    tags: ['academia', 'peito', 'compostos'],
    instructions: [
      'Deite num banco inclinado a 30-45° com barra na pegada pronada.',
      'Desça a barra lentamente até a parte superior do peito.',
      'Empurre a barra para cima até os cotovelos estenderem sem travar.',
    ],
    tips: ['Mantenha a escápula retraída e os pés no chão.'],
  },
  {
    source: 'metacore',
    name: 'Supino Declinado com Halteres',
    freeDbId: 'Decline_Dumbbell_Flyes',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral (feixe esternal inferior)',
    secondaryMuscles: ['Tríceps'],
    equipment: 'halteres',
    tags: ['academia', 'peito', 'isolamento'],
    instructions: [
      'Deite num banco declinado segurando halteres com pegada neutra.',
      'Abra os braços em arco até sentir o alongamento no peito.',
      'Feche de volta contraindo o peitoral.',
    ],
    tips: ['Ligeiro cotovelo dobrado protege a articulação do ombro.'],
  },
  {
    source: 'metacore',
    name: 'Pullover com Haltere',
    freeDbId: 'Bent-Arm_Dumbbell_Pullover',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral (feixe esternal)',
    secondaryMuscles: ['Grande dorsal', 'Serrátil'],
    equipment: 'halteres',
    tags: ['academia', 'peito', 'costas', 'expansão torácica'],
    instructions: [
      'Deite transversal num banco com a cabeça na borda e haltere com as duas mãos.',
      'Abaixe o haltere para trás da cabeça em arco.',
      'Retorne para a posição inicial.',
    ],
    tips: ['Inspire fundo durante a descida para expandir a caixa torácica.'],
  },
  {
    source: 'metacore',
    name: 'Flexão Inclinada (Declinada)',
    freeDbId: 'Decline_Push-Up',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral superior',
    secondaryMuscles: ['Deltóide anterior', 'Tríceps'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'peito'],
    instructions: [
      'Eleve os pés numa cadeira ou superfície elevada.',
      'Execute uma flexão convencional com o corpo inclinado para frente.',
    ],
    tips: ['Quanto mais alto os pés, maior o recrutamento do peitoral superior.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento com Salto (Jump Squat)',
    freeDbId: 'Bodyweight_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo máximo', 'Panturrilha'],
    equipment: 'peso_corporal',
    tags: ['casa', 'cardio', 'hiit', 'pliometria'],
    instructions: [
      'Agache com os pés na largura dos ombros.',
      'Empurre o chão explosivamente e salte.',
      'Pouse suavemente voltando à posição agachada.',
    ],
    tips: ['Pouso suave evita impacto excessivo nas articulações.'],
  },

  // ─── COSTAS (adicionais) ─────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Puxada na Polia Alta (Close Grip)',
    freeDbId: 'Close-Grip_Front_Lat_Pulldown',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps', 'Romboides'],
    equipment: 'máquina',
    tags: ['academia', 'costas', 'puxada'],
    instructions: [
      'Ajuste a barra fechada (triângulo) na polia alta.',
      'Sente com as coxas presas sob o suporte e puxe até o esterno.',
      'Retorne controlado.',
    ],
    tips: ['Incline levemente o tronco para trás e priorize apertar o dorsal.'],
  },
  {
    source: 'metacore',
    name: 'Remada Sentada no Cabo',
    freeDbId: 'Seated_Cable_Rows',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Romboides', 'Bíceps', 'Trapézio médio'],
    equipment: 'cabo',
    tags: ['academia', 'costas', 'remada'],
    instructions: [
      'Sente na máquina de remada com joelhos levemente dobrados.',
      'Puxe o triângulo até o umbigo retraindo as escápulas.',
      'Retorne estendendo os braços controladamente.',
    ],
    tips: ['Não curve a lombar — mantenha coluna neutra.'],
  },
  {
    source: 'metacore',
    name: 'Remada T-Bar',
    freeDbId: 'Lying_T-Bar_Row',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Romboides', 'Bíceps'],
    equipment: 'barra',
    tags: ['academia', 'costas', 'remada'],
    instructions: [
      'Posicione-se sobre a barra em T com o peito no suporte.',
      'Puxe a barra até o peito retraindo as escápulas.',
      'Abaixe controladamente.',
    ],
    tips: ['Mantenha o core contraído para proteger a lombar.'],
  },
  {
    source: 'metacore',
    name: 'Bom Dia (Good Morning)',
    freeDbId: 'Good_Morning',
    bodyPart: 'costas',
    targetMuscle: 'Eretor da espinha',
    secondaryMuscles: ['Isquiotibiais', 'Glúteo'],
    equipment: 'barra',
    tags: ['academia', 'lombar', 'posterior'],
    instructions: [
      'Coloque a barra nos trapézios e fique em pé com os pés na largura do quadril.',
      'Incline o tronco para frente mantendo a coluna neutra até o torso ficar paralelo ao chão.',
      'Retorne estendendo o quadril.',
    ],
    tips: ['Nunca arredonde a lombar. Carga leve no aprendizado.'],
  },
  {
    source: 'metacore',
    name: 'Hiperextensão Lombar',
    freeDbId: 'Hyperextensions_Back_Extensions',
    bodyPart: 'costas',
    targetMuscle: 'Eretor da espinha',
    secondaryMuscles: ['Glúteo máximo', 'Isquiotibiais'],
    equipment: 'máquina',
    tags: ['academia', 'lombar', 'postura'],
    instructions: [
      'Posicione-se no banco de hiperextensão com os quadris na almofada.',
      'Abaixe o tronco até 90° e suba até ficar alinhado com o corpo.',
      'Evite hiperestender para além da linha do quadril.',
    ],
    tips: ['Peso no peito aumenta a intensidade gradualmente.'],
  },
  {
    source: 'metacore',
    name: 'Remada com Elástico',
    freeDbId: 'Bent_Over_Two-Dumbbell_Row',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Romboides', 'Bíceps'],
    equipment: 'elástico',
    tags: ['casa', 'costas', 'elástico'],
    instructions: [
      'Prenda o elástico em uma superfície na altura do peito.',
      'Puxe as extremidades do elástico em direção ao torso retraindo as escápulas.',
      'Retorne controladamente.',
    ],
    tips: ['Mantenha os cotovelos próximos ao corpo para maior ativação do dorsal.'],
  },

  // ─── PERNA (adicionais) ───────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Extensão de Perna na Máquina',
    freeDbId: 'Leg_Extensions',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: [],
    equipment: 'máquina',
    tags: ['academia', 'perna', 'isolamento', 'quadríceps'],
    instructions: [
      'Ajuste o banco e os suportes da máquina ao seu tamanho.',
      'Estenda as pernas até a articulação do joelho travar levemente.',
      'Abaixe controladamente.',
    ],
    tips: ['Não trave o joelho com impacto — estenda suavemente.'],
  },
  {
    source: 'metacore',
    name: 'Hack Squat na Máquina',
    freeDbId: 'Hack_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Isquiotibiais'],
    equipment: 'máquina',
    tags: ['academia', 'perna', 'agachamento'],
    instructions: [
      'Posicione-se na máquina com ombros nos suportes e pés na plataforma.',
      'Desça até os joelhos atingirem ~90°.',
      'Empurre de volta com os calcanhares.',
    ],
    tips: ['Posição dos pés na plataforma muda o enfoque muscular.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento Frontal',
    freeDbId: 'Front_Squat_Clean_Grip',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Core', 'Glúteo'],
    equipment: 'barra',
    tags: ['academia', 'perna', 'compostos'],
    instructions: [
      'Apoie a barra nos deltoides anteriores com cotovelos elevados.',
      'Mantenha o torso o mais ereto possível durante a descida.',
      'Agache até as coxas ficarem paralelas ao chão.',
    ],
    tips: ['Exige boa mobilidade de tornozelo e ombro.'],
  },
  {
    source: 'metacore',
    name: 'Afundo com Barra',
    freeDbId: 'Barbell_Lunge',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Isquiotibiais'],
    equipment: 'barra',
    tags: ['academia', 'perna', 'unilateral'],
    instructions: [
      'Barra nos trapézios, dê um passo à frente.',
      'Desça até o joelho traseiro quase tocar o chão.',
      'Empurre de volta e alterne as pernas.',
    ],
    tips: ['Joelho da frente não deve ultrapassar a ponta do pé.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento Búlgaro',
    freeDbId: 'Split_Squat_with_Dumbbells',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Isquiotibiais'],
    equipment: 'halteres',
    tags: ['academia', 'perna', 'unilateral'],
    instructions: [
      'Apoie o pé traseiro num banco, segure halteres lateralmente.',
      'Desça o quadril até a coxa da frente ficar paralela ao chão.',
      'Suba empurrando com o calcanhar da perna da frente.',
    ],
    tips: ['Mantenha o tronco ereto; quanto mais longe o pé, mais glúteo.'],
  },
  {
    source: 'metacore',
    name: 'Elevação de Panturrilha em Pé',
    freeDbId: 'Rocking_Standing_Calf_Raise',
    bodyPart: 'perna',
    targetMuscle: 'Panturrilha (gastrocnêmio)',
    secondaryMuscles: ['Solear'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'panturrilha'],
    instructions: [
      'Fique na ponta dos pés e abaixe os calcanhares lentamente.',
      'Eleve novamente contraindo a panturrilha no topo.',
    ],
    tips: ['Adicione peso para progressão; amplitude total é fundamental.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento Sumo',
    freeDbId: 'Plie_Dumbbell_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Adutores',
    secondaryMuscles: ['Quadríceps', 'Glúteo'],
    equipment: 'halteres',
    tags: ['academia', 'casa', 'perna', 'adutores'],
    instructions: [
      'Pés bem abertos com pontas para fora segurando um haltere com as duas mãos.',
      'Desça mantendo o tronco ereto até as coxas ficarem paralelas.',
      'Suba empurrando com os calcanhares.',
    ],
    tips: ['Pontas dos pés seguem a direção dos joelhos.'],
  },
  {
    source: 'metacore',
    name: 'Leg Press 45°',
    freeDbId: 'Leg_Press',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Isquiotibiais'],
    equipment: 'máquina',
    tags: ['academia', 'perna', 'compostos'],
    instructions: [
      'Sente na máquina e posicione os pés na plataforma na largura dos ombros.',
      'Retire os travas e abaixe a plataforma controladamente até ~90° nos joelhos.',
      'Empurre de volta sem travar os joelhos.',
    ],
    tips: ['Pés altos = mais glúteo; pés baixos = mais quadríceps.'],
  },
  {
    source: 'metacore',
    name: 'Cadeira Adutora',
    freeDbId: 'Adductor',
    bodyPart: 'perna',
    targetMuscle: 'Adutores',
    secondaryMuscles: [],
    equipment: 'máquina',
    tags: ['academia', 'perna', 'isolamento'],
    instructions: [
      'Sente na máquina adutora com as coxas nos suportes.',
      'Feche as pernas contra a resistência da máquina.',
      'Retorne controladamente.',
    ],
    tips: ['Execute em cadência lenta para ativar melhor os adutores.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento Livre (Peso Corporal)',
    freeDbId: 'Bodyweight_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'iniciante'],
    instructions: [
      'Pés na largura dos ombros, braços à frente ou cruzados.',
      'Desça mantendo joelhos alinhados com os pés.',
      'Suba empurrando com os calcanhares.',
    ],
    tips: ['Iniciantes: use cadeira atrás para guiar a profundidade.'],
  },

  // ─── GLÚTEO (adicionais) ──────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Glúteo no Cabo (Kickback)',
    freeDbId: 'One-Legged_Cable_Kickback',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais'],
    equipment: 'cabo',
    tags: ['academia', 'glúteo', 'isolamento'],
    instructions: [
      'Prenda a tornozeleira no cabo baixo e fique de costas para a polia.',
      'Chute a perna para trás contraindo o glúteo no pico.',
      'Retorne controladamente.',
    ],
    tips: ['Não gire o quadril — mova só a perna.'],
  },
  {
    source: 'metacore',
    name: 'Ponte de Glúteo',
    freeDbId: 'Barbell_Glute_Bridge',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'glúteo', 'iniciante'],
    instructions: [
      'Deite de costas com joelhos dobrados e pés no chão.',
      'Eleve o quadril contraindo o glúteo e mantendo core ativado.',
      'Abaixe sem tocar o chão e repita.',
    ],
    tips: ['Adicione peso no quadril para progredir.'],
  },
  {
    source: 'metacore',
    name: 'Abdução com Elástico (Monster Walk)',
    freeDbId: 'Monster_Walk',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo médio',
    secondaryMuscles: ['TFL'],
    equipment: 'elástico',
    tags: ['casa', 'academia', 'glúteo', 'abdução'],
    instructions: [
      'Coloque o elástico nos tornozelos ou joelhos.',
      'Em semi-agachamento, ande lateralmente mantendo tensão constante no elástico.',
    ],
    tips: ['Mantenha os pés paralelos — evite rodar os quadris.'],
  },
  {
    source: 'metacore',
    name: 'Abdução na Máquina',
    freeDbId: 'Thigh_Adductor',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo médio',
    secondaryMuscles: ['TFL'],
    equipment: 'máquina',
    tags: ['academia', 'glúteo', 'isolamento', 'abdução'],
    instructions: [
      'Sente na máquina abdutora com as coxas nos suportes.',
      'Abra as pernas contra a resistência.',
      'Retorne controladamente.',
    ],
    tips: ['Ponta do pé para dentro recruta mais glúteo médio.'],
  },
  {
    source: 'metacore',
    name: 'Afundo Reverso',
    freeDbId: 'Dumbbell_Rear_Lunge',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Quadríceps', 'Isquiotibiais'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'glúteo'],
    instructions: [
      'Em pé, dê um passo para trás até o joelho traseiro quase tocar o chão.',
      'Empurre com o pé da frente para voltar à posição inicial.',
      'Alterne as pernas.',
    ],
    tips: ['Menos impacto no joelho anterior do que o afundo tradicional.'],
  },

  // ─── OMBRO (adicionais) ───────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Desenvolvimento com Barra (Press Militar)',
    freeDbId: 'Seated_Barbell_Military_Press',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide (feixe anterior e médio)',
    secondaryMuscles: ['Tríceps', 'Trapézio'],
    equipment: 'barra',
    tags: ['academia', 'ombro', 'compostos'],
    instructions: [
      'Sente ou fique em pé com barra na pegada um pouco além da largura dos ombros.',
      'Empurre a barra acima da cabeça até os cotovelos se estenderem.',
      'Abaixe controladamente até a altura dos ombros.',
    ],
    tips: ['Núcleo ativado; evite hiperestender a lombar.'],
  },
  {
    source: 'metacore',
    name: 'Arnold Press',
    freeDbId: 'Kettlebell_Arnold_Press',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide (todos os feixes)',
    secondaryMuscles: ['Tríceps', 'Trapézio'],
    equipment: 'halteres',
    tags: ['academia', 'ombro'],
    instructions: [
      'Segure os halteres na frente do corpo com palmas voltadas para você.',
      'Empurre para cima e gire as palmas para frente ao longo do movimento.',
      'Retorne com a rotação inversa.',
    ],
    tips: ['O giro trabalha todos os feixes do deltóide.'],
  },
  {
    source: 'metacore',
    name: 'Face Pull no Cabo',
    freeDbId: 'Face_Pull',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide posterior',
    secondaryMuscles: ['Manguito rotador', 'Romboides'],
    equipment: 'cabo',
    tags: ['academia', 'ombro', 'postura', 'saúde'],
    instructions: [
      'Ajuste a polia na altura do rosto com corda dupla.',
      'Puxe em direção ao rosto, separando as mãos.',
      'Retorno controlado.',
    ],
    tips: ['Essencial para saúde do ombro — não negligencie.'],
  },
  {
    source: 'metacore',
    name: 'Elevação Frontal com Halteres',
    freeDbId: 'Front_Raise_And_Pullover',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide anterior',
    secondaryMuscles: ['Peitoral superior'],
    equipment: 'halteres',
    tags: ['academia', 'ombro', 'isolamento'],
    instructions: [
      'Segure os halteres lateralmente com palmas para baixo.',
      'Eleve os braços à frente até a altura dos ombros.',
      'Abaixe controladamente.',
    ],
    tips: ['Evite usar o tronco para balançar os pesos.'],
  },
  {
    source: 'metacore',
    name: 'Rotação Interna/Externa com Elástico',
    freeDbId: 'External_Rotation_with_Band',
    bodyPart: 'ombro',
    targetMuscle: 'Manguito rotador',
    secondaryMuscles: [],
    equipment: 'elástico',
    tags: ['casa', 'academia', 'ombro', 'prevenção', 'saúde'],
    instructions: [
      'Com o cotovelo a 90° preso ao lado do corpo, gire o antebraço para fora (externa) ou para dentro (interna).',
      'Execute 15-20 repetições lentas em cada sentido.',
    ],
    tips: ['Exercício preventivo fundamental — use carga mínima.'],
  },
  {
    source: 'metacore',
    name: 'Encolhimento de Ombros com Halteres',
    freeDbId: 'Dumbbell_Shrug',
    bodyPart: 'ombro',
    targetMuscle: 'Trapézio',
    secondaryMuscles: ['Elevador da escápula'],
    equipment: 'halteres',
    tags: ['academia', 'trapézio', 'ombro'],
    instructions: [
      'Segure os halteres ao lado do corpo.',
      'Eleve os ombros em direção às orelhas.',
      'Abaixe lentamente.',
    ],
    tips: ['Sem girar os ombros — movimento vertical puro.'],
  },
  {
    source: 'metacore',
    name: 'Remada Alta no Cabo',
    freeDbId: 'Kneeling_High_Pulley_Row',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide médio',
    secondaryMuscles: ['Trapézio', 'Bíceps'],
    equipment: 'cabo',
    tags: ['academia', 'ombro', 'trapézio'],
    instructions: [
      'Segure a barra reta na polia baixa com pegada pronada estreita.',
      'Puxe até a barra alcançar a altura do queixo com cotovelos acima das mãos.',
      'Retorne controladamente.',
    ],
    tips: ['Cotovelos sempre acima dos punhos durante o movimento.'],
  },

  // ─── BÍCEPS (adicionais) ──────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Rosca Inclinada com Halteres',
    freeDbId: 'Alternate_Incline_Dumbbell_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'halteres',
    tags: ['academia', 'bíceps', 'isolamento'],
    instructions: [
      'Deite num banco inclinado (45-60°) e deixe os braços esticados.',
      'Enrole os halteres alternando os braços com a palma virada para cima.',
    ],
    tips: ['O alongamento inicial recruta mais fibras do bíceps.'],
  },
  {
    source: 'metacore',
    name: 'Rosca Concentrada',
    freeDbId: 'Concentration_Curls',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial (pico)',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'bíceps', 'isolamento', 'pico'],
    instructions: [
      'Sente numa cadeira, cotovelo apoiado na parte interna da coxa.',
      'Enrole o haltere em direção ao ombro.',
      'Abaixe controladamente.',
    ],
    tips: ['Máxima isolação do bíceps; pronação no final aumenta o pico.'],
  },
  {
    source: 'metacore',
    name: 'Rosca com Elástico',
    freeDbId: 'Cable_Preacher_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquiorradial'],
    equipment: 'elástico',
    tags: ['casa', 'bíceps', 'elástico'],
    instructions: [
      'Pise no elástico e segure as extremidades.',
      'Enrole os braços contraindo o bíceps.',
      'Retorne controladamente.',
    ],
    tips: ['A tensão do elástico aumenta ao longo do movimento — mais estímulo no pico.'],
  },

  // ─── TRÍCEPS (adicionais) ────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Tríceps Pulley (Pushdown)',
    freeDbId: 'Triceps_Pushdown',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'cabo',
    tags: ['academia', 'tríceps', 'isolamento'],
    instructions: [
      'Segure a barra ou corda na polia alta.',
      'Empurre para baixo até os cotovelos se estenderem com os braços ao lado do corpo.',
      'Retorne controladamente.',
    ],
    tips: ['Cotovelos fixos ao lado do corpo durante todo o movimento.'],
  },
  {
    source: 'metacore',
    name: 'Fundinho (Bench Dip)',
    freeDbId: 'Bench_Dips',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Deltóide anterior'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'funcional'],
    instructions: [
      'Mãos no banco atrás do corpo, pernas estendidas à frente.',
      'Dobre os cotovelos abaixando o quadril.',
      'Empurre de volta à posição inicial.',
    ],
    tips: ['Quanto mais longe os pés, maior a dificuldade.'],
  },
  {
    source: 'metacore',
    name: 'Extensão de Tríceps com Haltere Unilateral',
    freeDbId: 'Dumbbell_One-Arm_Triceps_Extension',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça longa)',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'tríceps', 'isolamento'],
    instructions: [
      'Em pé ou sentado, eleve um haltere acima da cabeça.',
      'Abaixe atrás da cabeça dobrando o cotovelo.',
      'Estenda de volta.',
    ],
    tips: ['Mantenha o cotovelo apontado para cima durante todo o movimento.'],
  },

  // ─── ANTEBRAÇO/PUNHO ─────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Rosca de Punho',
    freeDbId: 'Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench',
    bodyPart: 'antebraço',
    targetMuscle: 'Flexores do punho',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'antebraço', 'isolamento'],
    instructions: [
      'Sente com o antebraço apoiado na coxa e o punho fora do joelho.',
      'Abaixe e eleve o haltere flexionando o punho.',
    ],
    tips: ['Movimento pequeno e controlado; nunca use carga excessiva.'],
  },
  {
    source: 'metacore',
    name: 'Extensão de Punho',
    freeDbId: 'Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench',
    bodyPart: 'antebraço',
    targetMuscle: 'Extensores do punho',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'antebraço', 'prevenção'],
    instructions: [
      'Antebraço apoiado com palma para baixo.',
      'Eleve o punho (extensão) e abaixe controladamente.',
    ],
    tips: ['Importante para prevenção de epicondilite.'],
  },
  {
    source: 'metacore',
    name: 'Pronação e Supinação com Haltere',
    freeDbId: 'Seated_Dumbbell_Palms-Down_Wrist_Curl',
    bodyPart: 'antebraço',
    targetMuscle: 'Pronadores e supinadores',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'antebraço', 'mobilidade'],
    instructions: [
      'Segure um haltere vertical, cotovelo a 90°.',
      'Gire o antebraço de supinação (palma para cima) para pronação (palma para baixo).',
    ],
    tips: ['Escopo de movimento completo; peso leve.'],
  },
  {
    source: 'metacore',
    name: 'Strengthener de Pegada (Gripper)',
    bodyPart: 'antebraço',
    targetMuscle: 'Flexores dos dedos',
    secondaryMuscles: ['Músculos intrínsecos da mão'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'força de pegada'],
    instructions: [
      'Segure um gripper de mão e aperte totalmente.',
      'Abra devagar e repita.',
    ],
    tips: ['Treine ambas as mãos igualmente.'],
  },

  // ─── ABDÔMEN / CORE (adicionais) ──────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Prancha',
    freeDbId: 'Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Core (transverso abdominal)',
    secondaryMuscles: ['Glúteo', 'Lombar'],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'estabilidade'],
    instructions: [
      'Apoie-se nos antebraços e pontas dos pés formando uma linha reta.',
      'Mantenha o abdômen contraído e os quadris alinhados.',
      'Sustente pelo tempo determinado.',
    ],
    tips: ['Respire normalmente; não segure a respiração.'],
  },
  {
    source: 'metacore',
    name: 'Elevação de Pernas Suspensa',
    freeDbId: 'Hanging_Leg_Raise',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal inferior',
    secondaryMuscles: ['Hip flexors', 'Core'],
    equipment: 'peso_corporal',
    tags: ['academia', 'abdômen', 'força'],
    instructions: [
      'Pendurado na barra, contraia o abdômen e eleve as pernas até 90°.',
      'Abaixe sem balançar.',
    ],
    tips: ['Evite usar impulso — controle total.'],
  },
  {
    source: 'metacore',
    name: 'Twist Russo',
    freeDbId: 'Russian_Twist',
    bodyPart: 'abdômen',
    targetMuscle: 'Oblíquos',
    secondaryMuscles: ['Reto abdominal'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'oblíquos'],
    instructions: [
      'Sente com os joelhos dobrados e tronco inclinado 45°.',
      'Gire o tronco de lado a lado, tocando o chão com as mãos (ou haltere).',
    ],
    tips: ['Pés no chão para iniciantes; elevados para avançados.'],
  },
  {
    source: 'metacore',
    name: 'Mountain Climber',
    freeDbId: 'Mountain_Climbers',
    bodyPart: 'abdômen',
    targetMuscle: 'Core',
    secondaryMuscles: ['Quadríceps', 'Ombros'],
    equipment: 'peso_corporal',
    tags: ['casa', 'cardio', 'hiit', 'core'],
    instructions: [
      'Posição de prancha com braços estendidos.',
      'Alterne joelhos em direção ao peito rapidamente.',
    ],
    tips: ['Mantenha os quadris baixos e o core ativado.'],
  },
  {
    source: 'metacore',
    name: 'Abdominal Bicicleta',
    freeDbId: 'Cross-Body_Crunch',
    bodyPart: 'abdômen',
    targetMuscle: 'Oblíquos e reto abdominal',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    tags: ['casa', 'abdômen', 'oblíquos'],
    instructions: [
      'Deite de costas com mãos atrás da cabeça.',
      'Alterne cotovelo com joelho oposto em movimento de bicicleta.',
    ],
    tips: ['Não puxe o pescoço — o movimento parte do abdômen.'],
  },
  {
    source: 'metacore',
    name: 'Dead Bug',
    freeDbId: 'Dead_Bug',
    bodyPart: 'abdômen',
    targetMuscle: 'Core (estabilizadores)',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'estabilidade', 'funcional'],
    instructions: [
      'Deite de costas com braços para cima e joelhos a 90°.',
      'Abaixe braço esquerdo e perna direita simultaneamente mantendo lombar no chão.',
      'Retorne e alterne.',
    ],
    tips: ['Lombar deve estar em contato com o chão durante todo o movimento.'],
  },
  {
    source: 'metacore',
    name: 'Prancha Lateral',
    freeDbId: 'Push_Up_to_Side_Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Oblíquos',
    secondaryMuscles: ['Core', 'Glúteo médio'],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'oblíquos'],
    instructions: [
      'Apoie-se no antebraço e na lateral do pé, formando linha reta.',
      'Mantenha o quadril elevado durante todo o tempo.',
    ],
    tips: ['Execute dos dois lados igualmente.'],
  },
  {
    source: 'metacore',
    name: 'Crunch com Cabo',
    freeDbId: 'Cable_Crunch',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal',
    secondaryMuscles: [],
    equipment: 'cabo',
    tags: ['academia', 'abdômen', 'com carga'],
    instructions: [
      'Ajoelhe de frente para a polia alta segurando a corda.',
      'Flexione o tronco para baixo contraindo o abdômen.',
      'Retorne devagar.',
    ],
    tips: ['Não use o peso do quadril — o movimento deve partir do abdômen.'],
  },
  {
    source: 'metacore',
    name: 'Hollow Body Hold',
    freeDbId: 'Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Core (transverso)',
    secondaryMuscles: ['Hip flexors'],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'ginástica', 'avançado'],
    instructions: [
      'Deite de costas e pressione a lombar no chão.',
      'Eleve ombros e pernas simultaneamente mantendo posição hollowed.',
      'Sustente pelo tempo determinado.',
    ],
    tips: ['Iniciantes: joelhos dobrados; avançados: pernas estendidas.'],
  },
  {
    source: 'metacore',
    name: 'Leg Raise Deitado',
    freeDbId: 'Flat_Bench_Lying_Leg_Raise',
    bodyPart: 'abdômen',
    targetMuscle: 'Reto abdominal inferior',
    secondaryMuscles: ['Hip flexors'],
    equipment: 'peso_corporal',
    tags: ['casa', 'abdômen'],
    instructions: [
      'Deite com as mãos sob o quadril.',
      'Eleve as pernas esticadas até 90° e abaixe sem tocar o chão.',
    ],
    tips: ['Lombar sempre em contato com o chão.'],
  },

  // ─── CARDIO / HIIT ────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Corrida na Esteira',
    freeDbId: 'Jogging_Treadmill',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Quadríceps', 'Panturrilha', 'Glúteo'],
    equipment: 'máquina',
    tags: ['academia', 'cardio', 'corrida'],
    instructions: [
      'Ajuste velocidade e inclinação conforme objetivo.',
      'Mantenha postura ereta e passada natural.',
    ],
    tips: ['Inclinação de 1% simula corrida ao ar livre na esteira.'],
  },
  {
    source: 'metacore',
    name: 'Pular Corda',
    freeDbId: 'Battling_Ropes',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Panturrilha', 'Ombros'],
    equipment: 'corda',
    tags: ['casa', 'academia', 'cardio', 'hiit'],
    instructions: [
      'Pule com os pés juntos ou alternados mantendo o core contraído.',
      'Punhos próximos ao corpo; movimentos dos braços mínimos.',
    ],
    tips: ['Comece com séries de 30s e vá aumentando gradualmente.'],
  },
  {
    source: 'metacore',
    name: 'Burpee',
    freeDbId: 'Freehand_Jump_Squat',
    bodyPart: 'cardio',
    targetMuscle: 'Corpo inteiro',
    secondaryMuscles: ['Peito', 'Quadríceps', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'hiit', 'funcional', 'cardio'],
    instructions: [
      'Do pé, desça para flexão, faça a flexão.',
      'Salte os pés para a posição de agachamento.',
      'Salte para cima com os braços acima da cabeça.',
    ],
    tips: ['Mantenha a sequência fluida; regule o ritmo para manter a forma.'],
  },
  {
    source: 'metacore',
    name: 'Polichinelo (Jumping Jack)',
    freeDbId: 'Freehand_Jump_Squat',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Deltóide', 'Adutores'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'aquecimento', 'cardio'],
    instructions: [
      'Em pé com os pés juntos e braços ao lado.',
      'Abra as pernas saltando e leve os braços acima da cabeça.',
      'Retorne à posição inicial.',
    ],
    tips: ['Ideal para aquecimento ou intervalos de recuperação ativa.'],
  },
  {
    source: 'metacore',
    name: 'Sprint Curto (Tiro)',
    freeDbId: 'Running_Treadmill',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Quadríceps', 'Glúteo', 'Panturrilha'],
    equipment: 'peso_corporal',
    tags: ['academia', 'hiit', 'corrida', 'potência'],
    instructions: [
      'Corra em velocidade máxima por 20-30 metros ou 10-15 segundos.',
      'Recupere por 1-2 minutos e repita.',
    ],
    tips: ['Aquecimento adequado antes de sprints é obrigatório.'],
  },
  {
    source: 'metacore',
    name: 'Remo Ergométrico',
    freeDbId: 'Rowing_Stationary',
    bodyPart: 'cardio',
    targetMuscle: 'Costas, pernas, core',
    secondaryMuscles: ['Bíceps', 'Ombros'],
    equipment: 'máquina',
    tags: ['academia', 'cardio', 'full body'],
    instructions: [
      'Sente no remo com pés nas braçadeiras e segure o cabo.',
      'Empurre com as pernas, incline o tronco para trás e puxe o cabo até o abdômen.',
      'Retorne na ordem inversa.',
    ],
    tips: ['60% do trabalho vem das pernas; 20% core; 20% braços.'],
  },
  {
    source: 'metacore',
    name: 'Skipping (Corrida no Lugar)',
    freeDbId: 'Running_Treadmill',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Quadríceps', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'cardio'],
    instructions: [
      'Corra no lugar elevando os joelhos até a altura do quadril.',
      'Mantenha os braços em movimento de corrida.',
    ],
    tips: ['Aumente a intensidade elevando mais os joelhos.'],
  },
  {
    source: 'metacore',
    name: 'Box Jump',
    freeDbId: 'Front_Box_Jump',
    bodyPart: 'cardio',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Panturrilha'],
    equipment: 'caixa',
    tags: ['academia', 'pliometria', 'hiit', 'potência'],
    instructions: [
      'Fique de frente para a caixa em posição de semissit.',
      'Salte e pouse sobre a caixa amortecendo com os joelhos.',
      'Desça e repita.',
    ],
    tips: ['Escolha altura que permita pouso seguro. Pouso suave é obrigatório.'],
  },

  // ─── FUNCIONAL / CASA ─────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Flexão de Braço Larga',
    freeDbId: 'Incline_Push-Up_Wide',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral (feixe lateral)',
    secondaryMuscles: ['Deltóide anterior', 'Tríceps'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'peito'],
    instructions: [
      'Mãos mais abertas que a largura dos ombros.',
      'Desça com os cotovelos abrindo 45° e empurre de volta.',
    ],
    tips: ['Maior abertura = mais peitoral lateral.'],
  },
  {
    source: 'metacore',
    name: 'Flexão de Braço Fechada',
    freeDbId: 'Incline_Push-Up_Close-Grip',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral medial'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'tríceps'],
    instructions: [
      'Mãos na largura dos ombros ou mais fechadas.',
      'Cotovelos ao lado do corpo na descida.',
    ],
    tips: ['Cotovelos próximos ao corpo = mais tríceps.'],
  },
  {
    source: 'metacore',
    name: 'Dip em Barras Paralelas',
    freeDbId: 'Parallel_Bar_Dip',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Peitoral inferior', 'Deltóide anterior'],
    equipment: 'barra',
    tags: ['academia', 'funcional', 'tríceps'],
    instructions: [
      'Apoie-se nas barras paralelas com o corpo ereto.',
      'Desça até os ombros ficarem abaixo dos cotovelos.',
      'Empurre de volta.',
    ],
    tips: ['Tronco ereto = mais tríceps; tronco inclinado = mais peito.'],
  },
  {
    source: 'metacore',
    name: 'Prancha com Toque no Ombro',
    freeDbId: 'Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Core (anti-rotação)',
    secondaryMuscles: ['Ombros'],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'funcional', 'estabilidade'],
    instructions: [
      'Posição de prancha alta (braços estendidos).',
      'Alterne tocar o ombro oposto sem rodar o quadril.',
    ],
    tips: ['Pés mais abertos aumentam estabilidade para iniciantes.'],
  },
  {
    source: 'metacore',
    name: 'Stepup no Banco',
    freeDbId: 'Barbell_Step_Ups',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'funcional'],
    instructions: [
      'Suba no banco com um pé, impulsionando com o calcanhar.',
      'Suba o segundo pé.',
      'Desça de volta alternando pé inicial.',
    ],
    tips: ['Adicione halteres para progressão.'],
  },
  {
    source: 'metacore',
    name: 'Superman (Extensão Dorsal no Chão)',
    freeDbId: 'Hyperextensions_With_No_Hyperextension_Bench',
    bodyPart: 'costas',
    targetMuscle: 'Eretor da espinha',
    secondaryMuscles: ['Glúteo', 'Ombros'],
    equipment: 'peso_corporal',
    tags: ['casa', 'lombar', 'postura'],
    instructions: [
      'Deite de bruços com braços estendidos à frente.',
      'Eleve simultaneamente braços, peito e pernas do chão.',
      'Segure por 2 segundos e abaixe.',
    ],
    tips: ['Movimento gentil — não force o pescoço.'],
  },
  {
    source: 'metacore',
    name: 'Bear Crawl',
    freeDbId: 'Bear_Crawl_Sled_Drags',
    bodyPart: 'abdômen',
    targetMuscle: 'Core',
    secondaryMuscles: ['Ombros', 'Quadríceps'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'core', 'mobilidade'],
    instructions: [
      'Em quatro apoios com joelhos 2 cm acima do chão.',
      'Avance movendo mão e joelho opostos simultaneamente.',
      'Mantenha as costas retas.',
    ],
    tips: ['Quadril nunca acima do nível da coluna.'],
  },
  {
    source: 'metacore',
    name: 'Handstand Hold (Parada de Mão)',
    freeDbId: 'Handstand_Push-Ups',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide',
    secondaryMuscles: ['Core', 'Tríceps'],
    equipment: 'peso_corporal',
    tags: ['calistenia', 'avançado', 'equilíbrio'],
    instructions: [
      'Encoste na parede e suba em parada de mão.',
      'Mantenha o core contraído e cotovelos levemente dobrados.',
      'Sustente pelo tempo determinado.',
    ],
    tips: ['Progrida de encostar na parede a estabilizar no centro.'],
  },
  {
    source: 'metacore',
    name: 'Pike Push-Up',
    freeDbId: 'Incline_Push-Up',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide anterior',
    secondaryMuscles: ['Tríceps', 'Tríceps'],
    equipment: 'peso_corporal',
    tags: ['casa', 'ombro', 'funcional'],
    instructions: [
      'Posição de V invertido com quadril elevado.',
      'Dobre os cotovelos e abaixe a cabeça entre as mãos.',
      'Empurre de volta.',
    ],
    tips: ['Progressão para handstand push-up.'],
  },
  {
    source: 'metacore',
    name: 'Dip em Cadeira',
    freeDbId: 'Bench_Dips',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: ['Deltóide anterior'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'iniciante'],
    instructions: [
      'Mãos na beira de uma cadeira com pernas estendidas.',
      'Dobre os cotovelos abaixando o quadril.',
      'Empurre de volta.',
    ],
    tips: ['Versão mais simples do fundinho para iniciantes.'],
  },
  {
    source: 'metacore',
    name: 'Pistol Squat (Agachamento Unilateral)',
    freeDbId: 'Kettlebell_Pistol_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Core', 'Tornozelo'],
    equipment: 'peso_corporal',
    tags: ['casa', 'calistenia', 'avançado', 'unilateral'],
    instructions: [
      'Em pé sobre uma perna com a outra estendida à frente.',
      'Agache na perna de apoio mantendo a outra levantada.',
      'Suba de volta sem perder o equilíbrio.',
    ],
    tips: ['Use apoio lateral no aprendizado; exige muito do tornozelo.'],
  },

  // ─── MOBILIDADE ───────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Rotação Torácica',
    freeDbId: 'External_Rotation',
    bodyPart: 'mobilidade',
    targetMuscle: 'Coluna torácica',
    secondaryMuscles: ['Oblíquos'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'postura'],
    instructions: [
      'Ajoelhe com uma mão atrás da cabeça.',
      'Gire o cotovelo para cima abrindo o tórax.',
      'Execute dos dois lados.',
    ],
    tips: ['Expirar na rotação aumenta amplitude.'],
  },
  {
    source: 'metacore',
    name: 'Hip 90/90 (Mobilidade de Quadril)',
    freeDbId: 'Kneeling_Hip_Flexor',
    bodyPart: 'mobilidade',
    targetMuscle: 'Rotadores do quadril',
    secondaryMuscles: ['Piriforme', 'TFL'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'quadril'],
    instructions: [
      'Sente no chão com as pernas a 90° frente e atrás.',
      'Incline o tronco sobre a perna da frente.',
      'Mude de lado.',
    ],
    tips: ['Progressão gradual; não force a amplitude.'],
  },
  {
    source: 'metacore',
    name: 'World Greatest Stretch',
    freeDbId: 'Worlds_Greatest_Stretch',
    bodyPart: 'mobilidade',
    targetMuscle: 'Quadril, ombro, coluna',
    secondaryMuscles: ['Isquiotibiais', 'Peitoral'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'aquecimento', 'full body'],
    instructions: [
      'Posição de afundo baixo com mão ipsilateral no chão.',
      'Gire o torso abrindo o braço para o teto.',
      'Faça também o windmill (braço para baixo).',
    ],
    tips: ['Um dos melhores exercícios de mobilidade total do corpo.'],
  },
  {
    source: 'metacore',
    name: 'Alongamento de Isquiotibiais (Faixa)',
    freeDbId: 'Chair_Leg_Extended_Stretch',
    bodyPart: 'mobilidade',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: [],
    equipment: 'elástico',
    tags: ['casa', 'mobilidade', 'alongamento', 'pós-treino'],
    instructions: [
      'Deite com uma faixa no pé e eleve a perna esticada.',
      'Aproxime a perna do tronco mantendo o joelho estendido.',
    ],
    tips: ['Respire profundamente e relaxe o músculo na expiração.'],
  },
  {
    source: 'metacore',
    name: 'Cat-Cow (Mobilidade de Coluna)',
    bodyPart: 'mobilidade',
    targetMuscle: 'Coluna (toda extensão)',
    secondaryMuscles: ['Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'coluna', 'aquecimento'],
    instructions: [
      'Em quatro apoios, alterne arqueamento e arredondamento da coluna.',
      'Inspire no arquear (cow) e expire no arredondar (cat).',
    ],
    tips: ['Ótimo para aquecimento e alívio de tensão lombar.'],
  },
  {
    source: 'metacore',
    name: 'Ankle Mobility Drill',
    freeDbId: 'Standing_Hip_Flexors',
    bodyPart: 'mobilidade',
    targetMuscle: 'Tornozelo',
    secondaryMuscles: ['Panturrilha'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'tornozelo', 'prevenção'],
    instructions: [
      'Ajoelhe com um pé à frente próximo da parede.',
      'Avance o joelho em direção à parede sem tirar o calcanhar do chão.',
      'Alterne lados.',
    ],
    tips: ['Essencial para agachamento profundo e saúde do joelho.'],
  },
  {
    source: 'metacore',
    name: 'Rolamento em Espuma (Foam Roll Costas)',
    bodyPart: 'mobilidade',
    targetMuscle: 'Coluna torácica',
    secondaryMuscles: ['Eretor da espinha'],
    equipment: 'peso_corporal',
    tags: ['casa', 'academia', 'recuperação', 'mobilidade'],
    instructions: [
      'Deite sobre o rolo na região torácica.',
      'Mova o corpo para frente e para trás para massagear a coluna.',
    ],
    tips: ['Pause em pontos de tensão por 30-60s.'],
  },
  {
    source: 'metacore',
    name: 'Pigeon Pose (Pombo — Quadril)',
    freeDbId: 'Kneeling_Hip_Flexor',
    bodyPart: 'mobilidade',
    targetMuscle: 'Piriforme',
    secondaryMuscles: ['Rotadores externos do quadril'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'quadril', 'pós-treino'],
    instructions: [
      'Em quatro apoios, avance um joelho entre as mãos.',
      'Estenda a perna oposta para trás.',
      'Deite o tronco sobre a perna dobrada.',
    ],
    tips: ['Sustente por 60-90s de cada lado para resultado.'],
  },

  // ─── AQUECIMENTO ATIVO ────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Rotação de Braços',
    freeDbId: 'Chest_And_Front_Of_Shoulder_Stretch',
    bodyPart: 'aquecimento',
    targetMuscle: 'Ombro (manguito rotador)',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'ombro'],
    instructions: [
      'Braços estendidos, faça círculos progressivos.',
      'Alterne para frente e para trás.',
    ],
    tips: ['Comece pequeno e aumente progressivamente o raio.'],
  },
  {
    source: 'metacore',
    name: 'Corrida Elevada no Lugar',
    freeDbId: 'Running_Treadmill',
    bodyPart: 'aquecimento',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'cardio'],
    instructions: ['Corra no lugar elevando joelhos ao nível do quadril por 30-60 segundos.'],
    tips: ['Ótimo para elevar temperatura central antes de treino.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento com Rotação de Ombro',
    freeDbId: 'Overhead_Squat',
    bodyPart: 'aquecimento',
    targetMuscle: 'Quadríceps + Ombros',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'mobilidade'],
    instructions: [
      'Agache e ao subir, eleve os braços rodando os ombros para trás.',
    ],
    tips: ['Ative mobilidade total em um único movimento.'],
  },
  {
    source: 'metacore',
    name: 'Leg Swing (Balanço de Perna)',
    freeDbId: 'Chair_Leg_Extended_Stretch',
    bodyPart: 'aquecimento',
    targetMuscle: 'Quadril',
    secondaryMuscles: ['Isquiotibiais'],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'mobilidade'],
    instructions: [
      'Apoie-se na parede e balance uma perna para frente e para trás.',
      'Faça também lateralmente.',
    ],
    tips: ['Amplitude progressiva; nunca force.'],
  },
  {
    source: 'metacore',
    name: 'Inchworm',
    freeDbId: 'Inchworm',
    bodyPart: 'aquecimento',
    targetMuscle: 'Isquiotibiais + Core',
    secondaryMuscles: ['Ombros'],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'mobilidade', 'full body'],
    instructions: [
      'Em pé, dobre para frente tocando o chão.',
      'Caminhe com as mãos até a posição de prancha.',
      'Retorne caminhando com os pés até as mãos.',
    ],
    tips: ['Mantenha os joelhos estendidos para máximo alongamento dos isquiotibiais.'],
  },
  {
    source: 'metacore',
    name: 'Lateral Shuffle',
    freeDbId: 'Side_Leg_Raises',
    bodyPart: 'aquecimento',
    targetMuscle: 'Adutores e abdutores',
    secondaryMuscles: ['Quadríceps'],
    equipment: 'peso_corporal',
    tags: ['casa', 'aquecimento', 'funcional'],
    instructions: [
      'Em semi-agachamento, mova lateralmente rápido por 5-6 passos.',
      'Retorne para o outro lado.',
    ],
    tips: ['Ideal para aquecimento de treinos de perna e HIIT.'],
  },

  // ─── LEVANTAMENTO COMPOSTO ────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Levantamento Terra',
    freeDbId: 'Romanian_Deadlift',
    bodyPart: 'costas',
    targetMuscle: 'Eretor da espinha',
    secondaryMuscles: ['Glúteo', 'Isquiotibiais', 'Trapézio'],
    equipment: 'barra',
    tags: ['academia', 'compostos', 'full body'],
    instructions: [
      'Pés na largura do quadril, barra sobre os pés.',
      'Dobrando os quadris e joelhos, agarre a barra com pegada pronada ou mista.',
      'Estenda quadris e joelhos simultaneamente até ficar ereto.',
      'Controle a descida.',
    ],
    tips: ['Coluna neutra é obrigatória. Comece com carga técnica.'],
  },
  {
    source: 'metacore',
    name: 'Power Clean',
    freeDbId: 'Power_Clean',
    bodyPart: 'costas',
    targetMuscle: 'Full body (cadeia posterior)',
    secondaryMuscles: ['Quadríceps', 'Trapézio', 'Core'],
    equipment: 'barra',
    tags: ['academia', 'levantamento olímpico', 'potência', 'avançado'],
    instructions: [
      'Pull inicial da barra com extensão explosiva dos quadris.',
      'Encolha os ombros e puxe a barra para o rack da frente.',
    ],
    tips: ['Exercício técnico — aprenda com progressões e coach.'],
  },
  {
    source: 'metacore',
    name: 'Supino Reto com Halteres',
    freeDbId: 'Dumbbell_Bench_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Deltóide anterior', 'Tríceps'],
    equipment: 'halteres',
    tags: ['academia', 'peito', 'compostos'],
    instructions: [
      'Deite num banco reto segurando halteres na altura do peito.',
      'Empurre verticalmente até os braços quase se estenderem.',
      'Abaixe controlado.',
    ],
    tips: ['Maior amplitude que o supino com barra.'],
  },
  {
    source: 'metacore',
    name: 'Terra Sumo',
    freeDbId: 'Sumo_Deadlift',
    bodyPart: 'perna',
    targetMuscle: 'Adutores e glúteo',
    secondaryMuscles: ['Quadríceps', 'Isquiotibiais'],
    equipment: 'barra',
    tags: ['academia', 'compostos', 'perna'],
    instructions: [
      'Pés bem abertos com pontas para fora, barra entre as pernas.',
      'Agarre a barra e estenda quadril e joelhos até ficar ereto.',
    ],
    tips: ['Variação de terra com mais ativação de adutores e menos lombar.'],
  },
  {
    source: 'metacore',
    name: 'Clean and Press',
    freeDbId: 'Clean_and_Press',
    bodyPart: 'ombro',
    targetMuscle: 'Full body',
    secondaryMuscles: ['Deltóide', 'Quadríceps', 'Core'],
    equipment: 'kettlebell',
    tags: ['academia', 'funcional', 'full body', 'potência'],
    instructions: [
      'Faça o clean do kettlebell até o ombro.',
      'Pressione acima da cabeça.',
      'Retorne ao chão.',
    ],
    tips: ['Integra força e potência num único movimento.'],
  },

  // ─── CALISTENIA AVANÇADA ──────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Muscle-Up',
    freeDbId: 'Muscle_Up',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal + Tríceps',
    secondaryMuscles: ['Peitoral', 'Core'],
    equipment: 'barra',
    tags: ['calistenia', 'avançado', 'barra'],
    instructions: [
      'Puxe-se acima da barra num único movimento explosivo.',
      'Transite para a posição de dip acima da barra.',
      'Empurre até os braços se estenderem.',
    ],
    tips: ['Requer barra fixa sólida e força de pull + dip combinados.'],
  },
  {
    source: 'metacore',
    name: 'L-Sit',
    freeDbId: 'Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Core (hip flexors)',
    secondaryMuscles: ['Tríceps', 'Ombros'],
    equipment: 'peso_corporal',
    tags: ['calistenia', 'avançado', 'core'],
    instructions: [
      'Apoie-se nas mãos (paralelas ou chão) com as pernas estendidas formando L.',
      'Sustente pelo tempo determinado.',
    ],
    tips: ['Progrida de pernas dobradas a completamente estendidas.'],
  },
  {
    source: 'metacore',
    name: 'Front Lever',
    freeDbId: 'Hanging_Leg_Raise',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal (comprimento total)',
    secondaryMuscles: ['Core', 'Peitoral'],
    equipment: 'barra',
    tags: ['calistenia', 'avançado', 'barra', 'força'],
    instructions: [
      'Pendurado na barra, estenda o corpo horizontalmente para frente.',
      'Mantenha os braços estendidos e o corpo reto.',
    ],
    tips: ['Progressão: tuck → half-tuck → straddle → full.'],
  },
  {
    source: 'metacore',
    name: 'Skin the Cat',
    freeDbId: 'Muscle_Up',
    bodyPart: 'ombro',
    targetMuscle: 'Manguito rotador',
    secondaryMuscles: ['Grande dorsal', 'Core'],
    equipment: 'barra',
    tags: ['calistenia', 'avançado', 'mobilidade', 'ombro'],
    instructions: [
      'Pendurado na barra, passe as pernas atrás e entre os braços.',
      'Retorne pelo mesmo caminho.',
    ],
    tips: ['Excelente para mobilidade de ombro; progrida aos poucos.'],
  },
  {
    source: 'metacore',
    name: 'One-Arm Push-Up',
    freeDbId: 'One_Arm_Dumbbell_Bench_Press',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral (unilateral)',
    secondaryMuscles: ['Tríceps', 'Core', 'Deltóide'],
    equipment: 'peso_corporal',
    tags: ['calistenia', 'avançado', 'peito', 'unilateral'],
    instructions: [
      'Posição de flexão com uma mão atrás das costas.',
      'Pés afastados para estabilidade.',
      'Desça controlado e empurre de volta.',
    ],
    tips: ['Progrida com apoio lateral antes do movimento completo.'],
  },
  {
    source: 'metacore',
    name: 'Handstand Push-Up',
    freeDbId: 'Handstand_Push-Ups',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide',
    secondaryMuscles: ['Tríceps', 'Core'],
    equipment: 'peso_corporal',
    tags: ['calistenia', 'avançado', 'ombro'],
    instructions: [
      'Na parada de mão com suporte de parede.',
      'Dobre os cotovelos descendo a cabeça em direção ao chão.',
      'Empurre de volta.',
    ],
    tips: ['Pike push-up é a progressão anterior obrigatória.'],
  },

  // ─── BÍCEPS (mais) ────────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Rosca 21 com Barra',
    freeDbId: 'Barbell_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquiorradial'],
    equipment: 'barra',
    tags: ['academia', 'bíceps', 'intensidade'],
    instructions: [
      '7 reps do fundo até a metade, 7 da metade até o topo, 7 reps completas.',
    ],
    tips: ['Técnica de sobrecarga — use carga mais leve que a usual.'],
  },
  {
    source: 'metacore',
    name: 'Rosca com Cabo (Cross Body)',
    freeDbId: 'Cross_Body_Hammer_Curl',
    bodyPart: 'bíceps',
    targetMuscle: 'Bíceps braquial',
    secondaryMuscles: ['Braquial'],
    equipment: 'cabo',
    tags: ['academia', 'bíceps', 'cabo'],
    instructions: [
      'De lado para a polia, puxe o cabo cruzando o corpo.',
    ],
    tips: ['Tensão constante ao longo de todo o movimento.'],
  },

  // ─── TRÍCEPS (mais) ───────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Tríceps Coice com Haltere',
    freeDbId: 'Tricep_Dumbbell_Kickback',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial (cabeça longa)',
    secondaryMuscles: [],
    equipment: 'halteres',
    tags: ['academia', 'tríceps', 'isolamento'],
    instructions: [
      'Apoiado num banco, cotovelo a 90° ao lado do corpo.',
      'Estenda o antebraço para trás contraindo o tríceps.',
      'Retorne controladamente.',
    ],
    tips: ['Cotovelo paralelo ao solo e fixo durante todo o movimento.'],
  },
  {
    source: 'metacore',
    name: 'Tríceps com Elástico',
    freeDbId: 'Speed_Band_Overhead_Triceps',
    bodyPart: 'tríceps',
    targetMuscle: 'Tríceps braquial',
    secondaryMuscles: [],
    equipment: 'elástico',
    tags: ['casa', 'tríceps', 'elástico'],
    instructions: [
      'Prenda o elástico acima da cabeça na porta.',
      'Puxe para baixo estendendo os cotovelos.',
    ],
    tips: ['Mantenha os cotovelos fixos ao lado do corpo.'],
  },

  // ─── CARDIO MÁQUINAS ──────────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Bicicleta Ergométrica',
    freeDbId: 'Elliptical_Trainer',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Quadríceps', 'Panturrilha'],
    equipment: 'máquina',
    tags: ['academia', 'cardio', 'máquina', 'baixo impacto'],
    instructions: [
      'Ajuste o banco na altura dos quadris.',
      'Pedaleie em cadência constante com resistência adequada ao objetivo.',
    ],
    tips: ['Ideal para quem tem impacto articular reduzido.'],
  },
  {
    source: 'metacore',
    name: 'Elíptico',
    freeDbId: 'Elliptical_Trainer',
    bodyPart: 'cardio',
    targetMuscle: 'Sistema cardiovascular',
    secondaryMuscles: ['Quadríceps', 'Glúteo', 'Panturrilha'],
    equipment: 'máquina',
    tags: ['academia', 'cardio', 'máquina', 'baixo impacto'],
    instructions: [
      'Mantenha postura ereta e use os braços para aumentar a intensidade.',
    ],
    tips: ['Baixo impacto articular — ótimo para recuperação ativa.'],
  },

  // ─── LEVANTAMENTO COMPOSTO (mais) ─────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Kettlebell Swing',
    freeDbId: 'One-Arm_Kettlebell_Swings',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais', 'Core', 'Ombros'],
    equipment: 'kettlebell',
    tags: ['academia', 'funcional', 'potência', 'full body'],
    instructions: [
      'Incline levemente o tronco e balance o kettlebell entre as pernas.',
      'Estenda quadris explosivamente impulsionando o kb à frente.',
      'Deixe o kb descer e repita o movimento de dobradiça.',
    ],
    tips: ['Movimento de quadril (hip hinge), não agachamento.'],
  },
  {
    source: 'metacore',
    name: 'Snatch com Haltere',
    freeDbId: 'Power_Clean',
    bodyPart: 'ombro',
    targetMuscle: 'Full body',
    secondaryMuscles: ['Glúteo', 'Trapézio', 'Deltóide'],
    equipment: 'halteres',
    tags: ['academia', 'funcional', 'potência', 'avançado'],
    instructions: [
      'Agache com haltere no chão.',
      'Levante explosivamente e traga o haltere acima da cabeça num movimento único.',
    ],
    tips: ['Exercício de potência — priorize técnica à carga.'],
  },
  {
    source: 'metacore',
    name: 'Thruster (Agachamento + Press)',
    freeDbId: 'Barbell_Hip_Thrust',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps + Deltóide',
    secondaryMuscles: ['Glúteo', 'Core'],
    equipment: 'halteres',
    tags: ['academia', 'funcional', 'hiit', 'full body'],
    instructions: [
      'Com halteres nos ombros, agache profundamente.',
      'Ao subir, impulsione os halteres acima da cabeça.',
    ],
    tips: ['Use o impulso do agachamento para ajudar no press.'],
  },

  // ─── FUNCIONAL/CASA (mais) ────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Prancha com Elevação de Quadril (Pike)',
    freeDbId: 'Push_Up_to_Side_Plank',
    bodyPart: 'abdômen',
    targetMuscle: 'Core',
    secondaryMuscles: ['Ombros', 'Isquiotibiais'],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'funcional'],
    instructions: [
      'Na posição de prancha, eleve o quadril formando um V invertido.',
      'Abaixe de volta controladamente.',
    ],
    tips: ['Mantém a tensão no core durante toda a execução.'],
  },
  {
    source: 'metacore',
    name: 'Escalador com Torção',
    freeDbId: 'Mountain_Climbers',
    bodyPart: 'abdômen',
    targetMuscle: 'Oblíquos',
    secondaryMuscles: ['Core', 'Ombros'],
    equipment: 'peso_corporal',
    tags: ['casa', 'core', 'oblíquos', 'hiit'],
    instructions: [
      'Posição de prancha alta.',
      'Traga o joelho em diagonal em direção ao cotovelo oposto.',
      'Alterne rapidamente.',
    ],
    tips: ['Versão mais intensa do mountain climber com foco nos oblíquos.'],
  },
  {
    source: 'metacore',
    name: 'Swing Lateral com Elástico',
    freeDbId: 'External_Rotation_with_Band',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo médio',
    secondaryMuscles: ['TFL', 'Abdutores'],
    equipment: 'elástico',
    tags: ['casa', 'glúteo', 'abdução'],
    instructions: [
      'Elástico nos tornozelos, fique em pé.',
      'Balance uma perna lateralmente mantendo o corpo estável.',
    ],
    tips: ['Controle o retorno para não deixar o elástico puxar de volta rápido.'],
  },
  {
    source: 'metacore',
    name: 'Superman com Alternância',
    freeDbId: 'Hyperextensions_With_No_Hyperextension_Bench',
    bodyPart: 'costas',
    targetMuscle: 'Eretor da espinha',
    secondaryMuscles: ['Glúteo', 'Isquiotibiais'],
    equipment: 'peso_corporal',
    tags: ['casa', 'lombar', 'funcional'],
    instructions: [
      'Deite de bruços.',
      'Eleve alternadamente o braço direito com a perna esquerda e vice-versa.',
    ],
    tips: ['Versão mais desafiadora que o superman bilateral.'],
  },
  {
    source: 'metacore',
    name: 'Chair Squat (Agachamento na Cadeira)',
    freeDbId: 'Chair_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo'],
    equipment: 'peso_corporal',
    tags: ['casa', 'iniciante', 'funcional'],
    instructions: [
      'Com uma cadeira atrás, agache até quase sentar.',
      'Suba antes de sentar completamente.',
    ],
    tips: ['Excelente ponto de partida para iniciantes aprenderem o padrão de agachamento.'],
  },
  {
    source: 'metacore',
    name: 'Glute Kickback de Joelhos',
    freeDbId: 'Glute_Kickback',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'glúteo', 'iniciante'],
    instructions: [
      'Em quatro apoios, chute um joelho para trás e para cima.',
      'Segure no topo e abaixe sem tocar o chão.',
    ],
    tips: ['Pode adicionar elástico acima dos joelhos para mais intensidade.'],
  },
  {
    source: 'metacore',
    name: 'Tuck Jump',
    freeDbId: 'Knee_Tuck_Jump',
    bodyPart: 'cardio',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Core', 'Panturrilha'],
    equipment: 'peso_corporal',
    tags: ['casa', 'pliometria', 'hiit'],
    instructions: [
      'Salte verticalmente trazendo os joelhos até o peito no pico do salto.',
      'Pouse suavemente em semissit.',
    ],
    tips: ['Pouso amortecido é essencial para proteger os joelhos.'],
  },
  {
    source: 'metacore',
    name: 'Frog Jump (Salto Sapo)',
    freeDbId: 'Weighted_Jump_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps + Glúteo',
    secondaryMuscles: ['Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'pliometria', 'funcional'],
    instructions: [
      'Agache fundo com as mãos no chão.',
      'Salte para frente aterrissando em agachamento.',
    ],
    tips: ['Ótimo para potência e trabalho aeróbico simultâneo.'],
  },
  {
    source: 'metacore',
    name: 'Wall Sit (Cadeira na Parede)',
    freeDbId: 'Sit_Squats',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'isométrico', 'resistência'],
    instructions: [
      'Apoie as costas na parede e abaixe até os joelhos ficarem a 90°.',
      'Sustente pelo tempo determinado.',
    ],
    tips: ['Não deixe os joelhos ultrapassarem a ponta dos pés.'],
  },
  {
    source: 'metacore',
    name: 'Cossack Squat (Agachamento Lateral)',
    freeDbId: 'Barbell_Side_Split_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Adutores',
    secondaryMuscles: ['Quadríceps', 'Glúteo'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'funcional', 'adutores'],
    instructions: [
      'Pés bem abertos, agache para um lado mantendo o outro joelho estendido.',
      'Alterne os lados.',
    ],
    tips: ['Exige mobilidade de quadril e tornozelo; progrida gradualmente.'],
  },
  {
    source: 'metacore',
    name: 'Nordic Curl (Curl Nórdico)',
    freeDbId: 'Lying_Machine_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Isquiotibiais',
    secondaryMuscles: ['Glúteo', 'Core'],
    equipment: 'peso_corporal',
    tags: ['academia', 'casa', 'prevenção', 'isquiotibiais'],
    instructions: [
      'Ajoelhe com os tornozelos presos, corpo ereto.',
      'Desça controladamente para frente usando os isquiotibiais.',
      'Empurre o chão para retornar.',
    ],
    tips: ['Um dos melhores exercícios preventivos de lesão de isquiotibiais.'],
  },
  {
    source: 'metacore',
    name: 'Tempo Push-Up (Flexão Lenta)',
    freeDbId: 'Clock_Push-Up',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Tríceps', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'intensidade'],
    instructions: [
      'Execute uma flexão com 3-4 segundos de descida, 2 segundos de pausa no fundo e subida explosiva.',
    ],
    tips: ['Maior tempo sob tensão mesmo sem adição de peso.'],
  },
  {
    source: 'metacore',
    name: 'Staggered Push-Up (Flexão Assimétrica)',
    freeDbId: 'Clock_Push-Up',
    bodyPart: 'peito',
    targetMuscle: 'Peitoral (unilateral)',
    secondaryMuscles: ['Tríceps', 'Core'],
    equipment: 'peso_corporal',
    tags: ['casa', 'funcional', 'progresso'],
    instructions: [
      'Uma mão à frente, outra mais atrás.',
      'Execute a flexão priorizando a carga no lado mais avançado.',
      'Alterne as mãos.',
    ],
    tips: ['Progressão intermediária rumo ao one-arm push-up.'],
  },
  {
    source: 'metacore',
    name: 'Agachamento com Haltere (Goblet)',
    freeDbId: 'Goblet_Squat',
    bodyPart: 'perna',
    targetMuscle: 'Quadríceps',
    secondaryMuscles: ['Glúteo', 'Core'],
    equipment: 'halteres',
    tags: ['academia', 'casa', 'perna', 'iniciante'],
    instructions: [
      'Segure um haltere verticalmente no peito (goblet).',
      'Agache fundo mantendo os joelhos alinhados com os pés.',
      'Suba empurrando com os calcanhares.',
    ],
    tips: ['O peso na frente ajuda a manter o torso ereto — ótimo para iniciantes.'],
  },

  // ─── POSTURA / PREVENÇÃO ──────────────────────────────────────────────────
  {
    source: 'metacore',
    name: 'Band Pull-Apart',
    freeDbId: 'Band_Pull_Apart',
    bodyPart: 'ombro',
    targetMuscle: 'Deltóide posterior',
    secondaryMuscles: ['Romboides', 'Manguito rotador'],
    equipment: 'elástico',
    tags: ['casa', 'academia', 'postura', 'ombro', 'prevenção'],
    instructions: [
      'Segure o elástico à frente com os braços estendidos.',
      'Abra os braços lateralmente puxando o elástico até o nível do peito.',
      'Retorne devagar.',
    ],
    tips: ['Faça em todos os treinos de empurrar para equilibrar o ombro.'],
  },
  {
    source: 'metacore',
    name: 'Remada com Elástico na Porta',
    freeDbId: 'Alternating_Kettlebell_Row',
    bodyPart: 'costas',
    targetMuscle: 'Grande dorsal',
    secondaryMuscles: ['Bíceps', 'Romboides'],
    equipment: 'elástico',
    tags: ['casa', 'costas', 'elástico'],
    instructions: [
      'Prenda o elástico na porta e puxe até o abdômen sentado no chão.',
    ],
    tips: ['Tensão constante — ótimo substituto da remada em máquina para casa.'],
  },
  {
    source: 'metacore',
    name: 'Extensão de Quadril em Pé',
    freeDbId: 'Hip_Extension_with_Bands',
    bodyPart: 'glúteo',
    targetMuscle: 'Glúteo máximo',
    secondaryMuscles: ['Isquiotibiais'],
    equipment: 'elástico',
    tags: ['casa', 'glúteo', 'elástico'],
    instructions: [
      'Com elástico no tornozelo, de frente para a parede.',
      'Estenda a perna para trás contraindo o glúteo.',
    ],
    tips: ['Mova o quadril, não apenas a perna.'],
  },
  {
    source: 'metacore',
    name: 'Chest Stretch (Alongamento de Peitoral)',
    freeDbId: 'Chin_To_Chest_Stretch',
    bodyPart: 'mobilidade',
    targetMuscle: 'Peitoral maior',
    secondaryMuscles: ['Deltóide anterior'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'pós-treino', 'postura'],
    instructions: [
      'Apoie um braço na parede com cotovelo a 90°.',
      'Gire o tronco para longe da parede.',
    ],
    tips: ['Ótimo para correção postural após treinos de empurrar.'],
  },
  {
    source: 'metacore',
    name: 'Mobilidade de Ombro (Towel Stretch)',
    freeDbId: 'Chest_And_Front_Of_Shoulder_Stretch',
    bodyPart: 'mobilidade',
    targetMuscle: 'Cápsula articular do ombro',
    secondaryMuscles: ['Manguito rotador'],
    equipment: 'peso_corporal',
    tags: ['casa', 'mobilidade', 'ombro', 'prevenção'],
    instructions: [
      'Segure uma toalha atrás das costas com ambas as mãos.',
      'Puxe levemente para cima com a mão superior.',
    ],
    tips: ['Faça após treinos de ombro para recuperação.'],
  },
];
