/**
 * Mapa CoreFit → gifdotreino.com — fonte de GIFs animados dos exercícios.
 * GERADO automaticamente (não editar à mão). Regenerar via scripts/mirrorGifDoTreino.
 *
 * Chave = nome PT-BR do nosso exercício (ExerciseSeed.name).
 * Valor = caminho ORIGEM no gifdotreino (relativo), usado só pelo script de espelhamento
 *         para baixar o arquivo. A URL pública final é derivada do slug + EXERCISE_MEDIA_BASE_URL.
 * Total: 224 exercícios com GIF (dos 242 do seed). Os demais mantêm free-exercise-db.
 */

export const GIF_DO_TREINO_SOURCE: Record<string, string> = {
  'Abdominal Bicicleta': 'Exercicios/Funcional e HIT/Elevação com Giro do Cotovelo Oposto para o Joelho.gif',
  'Abdominal Canivete': 'Exercicios/Funcional e HIT/V-Up com Bola de Estabilidade.gif',
  'Abdominal Completo': 'Exercicios/Mobilidade/Contração abdominal.gif',
  'Abdominal Infra (Elevação de Pernas)': 'Exercicios/Funcional e HIT/Elevação de Pernas estilo Sapo.gif',
  'Abdominal Remador': 'Exercicios/Funcional e HIT/V-Up com Bola de Estabilidade.gif',
  'Abdução com Elástico (Monster Walk)': 'Exercicios/Funcional e HIT/Caminhada Lateral com Faixa de Resistência.gif',
  'Abdução de Quadril na Máquina': 'Exercicios/Glúteos/Máquina de Abdução de Quadril.gif',
  'Abdução na Máquina': 'Exercicios/Glúteos/Máquina de Abdução de Quadril.gif',
  'Abdução na Polia': 'Exercicios/Glúteos/Abdução de quadril com cabo.gif',
  'Afundo (Lunge)': 'Exercicios/Pernas/Afundo com Halteres.gif',
  'Afundo Reverso': 'Exercicios/Pernas/Avanço Invertido.gif',
  'Afundo com Barra': 'Exercicios/Pernas/Afundo com Barra.gif',
  'Agachamento Búlgaro': 'Exercicios/Pernas/Agachamento Búlgaro com Halteres.gif',
  'Agachamento Frontal': 'Exercicios/Pernas/Agachamento Frontal.gif',
  'Agachamento Livre': 'Exercicios/Pernas/Agachamento Barra.gif',
  'Agachamento Livre (Peso Corporal)': 'Exercicios/Calistenia/Agachamento.gif',
  'Agachamento Sumo': 'Exercicios/Pernas/Agachamento Sumô com Halteres.gif',
  'Agachamento Sumô': 'Exercicios/Pernas/Agachamento Sumô com Halteres.gif',
  'Agachamento com Haltere (Goblet)': 'Exercicios/Pernas/Agachamento Goblet com Haltere.gif',
  'Agachamento com Salto (Jump Squat)': 'Exercicios/Calistenia/Agachamento com Salto.gif',
  'Agachamento no Smith': 'Exercicios/Pernas/Agachamento no Smith.gif',
  'Alongamento de Isquiotibiais (Faixa)': 'Exercicios/Mobilidade/Alongamento de Isquiotibiais deitado.gif',
  'Ankle Mobility Drill': 'Exercicios/Mobilidade/Alongamentos de pés e tornozelos.gif',
  'Arnold Press': 'Exercicios/Ombros/Desenvolvimento Arnold.gif',
  'Band Pull-Apart': 'Exercicios/Funcional e HIT/Crucifixo invertido com gymstick para deltoides posterior.gif',
  'Barra Fixa': 'Exercicios/Costas/Barra fixa.gif',
  'Barra Fixa Assistida': 'Exercicios/Calistenia/Barra fixa Assistida com Faixa Elástica.gif',
  'Barra Fixa Supinada': 'Exercicios/Calistenia/Barra Fixa com Pegada Supinada.gif',
  'Battle Rope': 'Exercicios/Crossfit/Corda de batalha.gif',
  'Bear Crawl': 'Exercicios/Funcional e HIT/Rastejo de Urso.gif',
  'Bicicleta Ergométrica': 'Exercicios/Cardio/Bike.gif',
  'Bird Dog': 'Exercicios/Funcional e HIT/Quadrúpede com elevação de braço e perna contralateral.gif',
  'Bom Dia (Good Morning)': 'Exercicios/Pernas/Bom dia.gif',
  'Box Jump': 'Exercicios/Crossfit/Salto na Caixa.gif',
  'Burpee': 'Exercicios/Crossfit/Burpees.gif',
  'Cadeira Adutora': 'Exercicios/Pernas/Máquina de Adução de Quadril.gif',
  'Cadeira Extensora': 'Exercicios/Pernas/Cadeira extensora.gif',
  'Cadeira Flexora': 'Exercicios/Pernas/Cadeira flexora.gif',
  'Caminhada na Esteira': 'Exercicios/Cardio/Esteira Ergométrica.gif',
  'Chair Squat (Agachamento na Cadeira)': 'Exercicios/Calistenia/Agachamento no Banco com Peso Corporal.gif',
  'Chest Press Máquina': 'Exercicios/Peitoral/Supino na máquina.gif',
  'Chest Stretch (Alongamento de Peitoral)': 'Exercicios/Mobilidade/Alongamento do Peito Acima da Cabeça.gif',
  'Clean and Press': 'Exercicios/Crossfit/Arranco e Levantamento com Kettlebell.gif',
  'Corrida Elevada no Lugar': 'Exercicios/Funcional e HIT/Corrida com Joelhos Altos.gif',
  'Corrida na Esteira': 'Exercicios/Cardio/Esteira Ergométrica.gif',
  'Cossack Squat (Agachamento Lateral)': 'Exercicios/Funcional e HIT/Agachamento Cossaco.gif',
  'Crossover Polia Alta': 'Exercicios/Peitoral/Cross over polia Alta.gif',
  'Crossover Polia Baixa': 'Exercicios/Peitoral/Cross over polia baixa.gif',
  'Crossover Polia Média': 'Exercicios/Peitoral/Cross over polia media.gif',
  'Crossover no Cabo': 'Exercicios/Peitoral/Cross over polia media.gif',
  'Crucifixo Inclinado com Halteres': 'Exercicios/Peitoral/Crucifixo com Halteres Inclinado.gif',
  'Crucifixo Inclinado na Máquina': 'Exercicios/Peitoral/Crucifixo Inclinado Cross.gif',
  'Crucifixo Inverso (Elevação Posterior)': 'Exercicios/Ombros/Voador invertido.gif',
  'Crucifixo com Halteres': 'Exercicios/Peitoral/Crucifixo com halteres.gif',
  'Crunch Abdominal': 'Exercicios/Mobilidade/Contração abdominal.gif',
  'Crunch com Cabo': 'Exercicios/Mobilidade/Contração abdominal.gif',
  'Crunch na Bola': 'Exercicios/Mobilidade/Contração abdominal.gif',
  'Desenvolvimento com Barra (Press Militar)': 'Exercicios/Ombros/Desenvolvimento militar com barra.gif',
  'Desenvolvimento com Halteres': 'Exercicios/Ombros/Desenvolvimento de Ombro no Banco com Halteres.gif',
  'Desenvolvimento na Máquina': 'Exercicios/Ombros/Desenvolvimento de ombro na máquina.gif',
  'Dip em Barras Paralelas': 'Exercicios/Calistenia/Paralelas na Barra.gif',
  'Dip em Cadeira': 'Exercicios/Calistenia/Dips na cadeira.gif',
  'Elevação Frontal': 'Exercicios/Ombros/Elevação frontal com halteres.gif',
  'Elevação Frontal com Halteres': 'Exercicios/Ombros/Elevação frontal com halteres.gif',
  'Elevação Lateral': 'Exercicios/Ombros/Elevação lateral de braços com halteres.gif',
  'Elevação Lateral na Máquina': 'Exercicios/Ombros/Elevação lateral na máquina.gif',
  'Elevação Lateral na Polia': 'Exercicios/Ombros/Elevação lateral de braços com cabo.gif',
  'Elevação Pélvica (Hip Thrust)': 'Exercicios/Glúteos/Elevação Pélvica Com Barra.gif',
  'Elevação Pélvica Máquina': 'Exercicios/Glúteos/Elevação Pélvica Na Máquina.gif',
  'Elevação de Panturrilha em Pé': 'Exercicios/Calistenia/Elevação de panturrilha em pé.gif',
  'Elíptico': 'Exercicios/Cardio/Máquina Elíptica.gif',
  'Encolhimento com Barra': 'Exercicios/Trapézio/Encolhimento de Barra.gif',
  'Encolhimento de Ombros com Barra': 'Exercicios/Trapézio/Encolhimento de Barra.gif',
  'Encolhimento de Ombros com Halteres': 'Exercicios/Trapézio/Encolhimento com Halteres.gif',
  'Encolhimento de Ombros na Polia': 'Exercicios/Trapézio/Encolhimento com Cabo.gif',
  'Escada Ergométrica': 'Exercicios/Cardio/Máquina Simulador Escada.gif',
  'Escalador com Torção': 'Exercicios/Funcional e HIT/Escalador de Montanha.gif',
  'Esteira (HIIT)': 'Exercicios/Cardio/Esteira Ergométrica.gif',
  'Extensão de Perna na Máquina': 'Exercicios/Pernas/Cadeira extensora.gif',
  'Extensão de Punho': 'Exercicios/Antebraços/Rosca de Punho Reversa com Barra.gif',
  'Extensão de Quadril em Pé': 'Exercicios/Funcional e HIT/Glúteo Coice em Pé com Faixa Elástica.gif',
  'Extensão de Tríceps Acima da Cabeça na Polia': 'Exercicios/Tríceps/Tríceps francês na polia com corda.gif',
  'Extensão de Tríceps com Haltere Unilateral': 'Exercicios/Tríceps/Extensão de tríceps com haltere unilateral sentado.gif',
  'Face Pull no Cabo': 'Exercicios/Trapézio/Face Pull.gif',
  'Farmer Walk': 'Exercicios/Crossfit/Caminhada com Halteres.gif',
  'Flexora em Pé': 'Exercicios/Pernas/Flexão de Pernas com Alavanca.gif',
  'Flexão Diamante': 'Exercicios/Calistenia/Flexão diamante.gif',
  'Flexão Inclinada (Declinada)': 'Exercicios/Calistenia/Flexão Declinada.gif',
  'Flexão de Braço': 'Exercicios/Calistenia/Flexão.gif',
  'Flexão de Braço Fechada': 'Exercicios/Calistenia/Flexão diamante.gif',
  'Flexão de Braço Larga': 'Exercicios/Calistenia/Flexão.gif',
  'Frog Jump (Salto Sapo)': 'Exercicios/Calistenia/Salto em Distância.gif',
  'Frog Pump': 'Exercicios/Funcional e HIT/Ponte de Glúteos.gif',
  'Front Lever': 'Exercicios/Calistenia/Puxada Front Lever.gif',
  'Fundinho (Bench Dip)': 'Exercicios/Tríceps/Tríceps no Banco.gif',
  'Glute Kickback de Joelhos': 'Exercicios/Glúteos/Quatro Apoios.gif',
  'Glúteo 4 Apoios (Donkey Kick)': 'Exercicios/Funcional e HIT/Coice de Burro.gif',
  'Glúteo na Máquina': 'Exercicios/Glúteos/Glúteo Coice Na Máquina.gif',
  'Glúteo no Cabo (Kickback)': 'Exercicios/Glúteos/Gluteos Coice nilateral Polia Baixa.gif',
  'Hack Squat na Máquina': 'Exercicios/Pernas/Agachamento na Máquina Hack.gif',
  'Handstand Hold (Parada de Mão)': 'Exercicios/Calistenia/Caminhada na Parada de Mão.gif',
  'Handstand Push-Up': 'Exercicios/Calistenia/Flexão com parada de mãos.gif',
  'Hip 90/90 (Mobilidade de Quadril)': 'Exercicios/Mobilidade/Alongamento de quadril 90-90.gif',
  'Hiperextensão Lombar': 'Exercicios/Eretor Lombar/Hiperextensão.gif',
  'Inchworm': 'Exercicios/Funcional e HIT/Minhoca.gif',
  'Jumping Jacks': 'Exercicios/Funcional e HIT/Polichinelos.gif',
  'Kettlebell Deadlift': 'Exercicios/Pernas/Levantamento Terra com Kettlebell.gif',
  'Kettlebell Swing': 'Exercicios/Crossfit/Swing de kettlebell.gif',
  'Lateral Shuffle': 'Exercicios/Funcional e HIT/Passo Lateral em Alta Velocidade.gif',
  'Leg Press 45°': 'Exercicios/Pernas/Leg Press.gif',
  'Leg Press 80°': 'Exercicios/Pernas/Leg Press.gif',
  'Leg Press Horizontal': 'Exercicios/Pernas/Leg Press Horizontal.gif',
  'Leg Raise Deitado': 'Exercicios/Funcional e HIT/Elevação de Pernas estilo Sapo.gif',
  'Levantamento Terra': 'Exercicios/Costas/Levantamento Terra.gif',
  'Mergulho (Tríceps Dip)': 'Exercicios/Calistenia/Mergulho de tríceps.gif',
  'Mergulho na Máquina': 'Exercicios/Tríceps/Mergulho de tríceps com alavanca.gif',
  'Mesa Flexora (Leg Curl Deitado)': 'Exercicios/Pernas/Mesa flexora.gif',
  'Mobilidade de Ombro (Towel Stretch)': 'Exercicios/Mobilidade/Alongamento do ombro com toalha.gif',
  'Mountain Climber': 'Exercicios/Funcional e HIT/Escalador de Montanha.gif',
  'Muscle-Up': 'Exercicios/Calistenia/Muscle up.gif',
  'Nordic Curl (Curl Nórdico)': 'Exercicios/Pernas/Flexão Nórdica.gif',
  'Oblíquo com Rotação': 'Exercicios/Mobilidade/Torção Oblíqua Sentada.gif',
  'One-Arm Push-Up': 'Exercicios/Calistenia/Flexão com um braço.gif',
  'Panturrilha Sentado': 'Exercicios/Panturrilhas/Elevação de Panturrilha Sentado com Alavanca.gif',
  'Panturrilha Unilateral': 'Exercicios/Panturrilhas/Levantamento de panturrilha com apoio de uma perna.gif',
  'Panturrilha com Halteres': 'Exercicios/Panturrilhas/Panturrilhas em Pé.gif',
  'Panturrilha em Pé (Calf Raise)': 'Exercicios/Panturrilhas/Elevação de Panturrilha em Máquina em pé.gif',
  'Panturrilha no Leg Press': 'Exercicios/Panturrilhas/Elevação de Panturrilha no Leg Press.gif',
  'Panturrilha no Smith': 'Exercicios/Panturrilhas/Elevação de Panturrilha no Smith.gif',
  'Paralelas Assistidas': 'Exercicios/Tríceps/Mergulhos Assistidos para Tríceps.gif',
  'Passada Caminhando': 'Exercicios/Pernas/Avanço com Barra.gif',
  'Peck Deck (Máquina)': 'Exercicios/Peitoral/Voador no pec deck.gif',
  'Pigeon Pose (Pombo — Quadril)': 'Exercicios/Mobilidade/Alongamento Piriforme.gif',
  'Pike Push-Up': 'Exercicios/Calistenia/Flexão Invertida.gif',
  'Pistol Squat (Agachamento Unilateral)': 'Exercicios/Calistenia/Agachamento pistola.gif',
  'Polichinelo (Jumping Jack)': 'Exercicios/Funcional e HIT/Polichinelos.gif',
  'Ponte de Glúteo': 'Exercicios/Funcional e HIT/Ponte de Glúteos.gif',
  'Power Clean': 'Exercicios/Crossfit/Power Clean.gif',
  'Pular Corda': 'Exercicios/Crossfit/Pular Corda.gif',
  'Pulldown com Braços Retos': 'Exercicios/Costas/Pullover com Cabo.gif',
  'Pullover com Haltere': 'Exercicios/Peitoral/Pullover com haltere.gif',
  'Pullover na Polia': 'Exercicios/Costas/Pullover com Cabo.gif',
  'Puxada Frente (Lat Pulldown)': 'Exercicios/Costas/Puxada Alta.gif',
  'Puxada Neutra': 'Exercicios/Costas/Puxada Alta com Triângulo.gif',
  'Puxada Supinada': 'Exercicios/Costas/Puxada Alta Invertida.gif',
  'Puxada na Polia Alta (Close Grip)': 'Exercicios/Costas/Puxada na Polia Alta com Pegada Fechada.gif',
  'Remada Alta no Cabo': 'Exercicios/Trapézio/Remada Alta com Cabo.gif',
  'Remada Articulada': 'Exercicios/Costas/Remada Sentada na Máquina.gif',
  'Remada Baixa no Cabo': 'Exercicios/Costas/Remada Sentada com Cabo.gif',
  'Remada Curvada com Barra': 'Exercicios/Costas/Remada Curvada com Barra.gif',
  'Remada Invertida': 'Exercicios/Costas/Remada Invertida.gif',
  'Remada Sentada no Cabo': 'Exercicios/Costas/Remada Sentada com Cabo.gif',
  'Remada T-Bar': 'Exercicios/Costas/Remada Curvada em T.gif',
  'Remada Unilateral com Haltere': 'Exercicios/Costas/Serrote.gif',
  'Remada com Elástico': 'Exercicios/Funcional e HIT/Remada sentada com faixa.gif',
  'Remada com Elástico na Porta': 'Exercicios/Funcional e HIT/Remada sentada com faixa.gif',
  'Remo Ergométrico': 'Exercicios/Costas/Máquina de remo.gif',
  'Rolamento em Espuma (Foam Roll Costas)': 'Exercicios/Mobilidade/Rolamento de espuma nas costas.gif',
  'Rosca 21 com Barra': 'Exercicios/Bíceps/Rosca Direta com Barra.gif',
  'Rosca Alternada com Halteres': 'Exercicios/Bíceps/Rosca alternada com halteres sentado.gif',
  'Rosca Concentrada': 'Exercicios/Bíceps/Rosca concentrada.gif',
  'Rosca Direta com Barra': 'Exercicios/Bíceps/Rosca Direta com Barra.gif',
  'Rosca Direta com Barra W': 'Exercicios/Bíceps/Rosca direta com barra w.gif',
  'Rosca Direta na Polia': 'Exercicios/Bíceps/Rosca no Cabo.gif',
  'Rosca Inclinada com Halteres': 'Exercicios/Bíceps/Rosca bíceps inclinada com halteres sentado.gif',
  'Rosca Inversa': 'Exercicios/Bíceps/Rosca Inversa com Halteres.gif',
  'Rosca Martelo': 'Exercicios/Bíceps/Rosca martelo.gif',
  'Rosca Martelo na Corda': 'Exercicios/Bíceps/Rosca martelo com corda.gif',
  'Rosca Scott (Preacher Curl)': 'Exercicios/Bíceps/Rosca Scott com Barra W.gif',
  'Rosca Scott Máquina': 'Exercicios/Bíceps/Rosca Scott com Alavanca.gif',
  'Rosca Scott com Halter': 'Exercicios/Bíceps/Rosca scott com halteres.gif',
  'Rosca Simultânea com Halteres': 'Exercicios/Bíceps/Rosca bíceps com halteres.gif',
  'Rosca Spider': 'Exercicios/Bíceps/Rosca spider com único haltere.gif',
  'Rosca com Cabo (Cross Body)': 'Exercicios/Bíceps/Rosca com cabo de um braço.gif',
  'Rosca com Elástico': 'Exercicios/Funcional e HIT/Rosca bíceps com faixa elástica.gif',
  'Rosca de Punho': 'Exercicios/Antebraços/Flexão de Punho com Halteres.gif',
  'Rotação Interna/Externa com Elástico': 'Exercicios/Mobilidade/Rotação externa de ombro com faixa elástica.gif',
  'Rotação Torácica': 'Exercicios/Mobilidade/Rotação da coluna torácica de joelhos.gif',
  'Rotação de Braços': 'Exercicios/Mobilidade/Círculos com os braços.gif',
  'Sissy Squat': 'Exercicios/Pernas/Agachamento Sissy.gif',
  'Skipping (Corrida no Lugar)': 'Exercicios/Funcional e HIT/Corrida Estacionária.gif',
  'Slam Ball': 'Exercicios/Crossfit/Bola medicinal lançada para cima e para baixo.gif',
  'Snatch com Haltere': 'Exercicios/Crossfit/Arremesso com haltere de um braço.gif',
  'Sprint Curto (Tiro)': 'Exercicios/Funcional e HIT/Corrida.gif',
  'Staggered Push-Up (Flexão Assimétrica)': 'Exercicios/Calistenia/Flexão.gif',
  'Stepup no Banco': 'Exercicios/Funcional e HIT/Subida no Step com Elevação de Joelhos.gif',
  'Stiff (Romanian Deadlift)': 'Exercicios/Pernas/Stiff com barra.gif',
  'Stiff com Halteres': 'Exercicios/Pernas/Stiff com Halter.gif',
  'Strengthener de Pegada (Gripper)': 'Exercicios/Antebraços/Hand Grip.gif',
  'Superman (Extensão Dorsal no Chão)': 'Exercicios/Eretor Lombar/Superman.gif',
  'Superman com Alternância': 'Exercicios/Eretor Lombar/Superman.gif',
  'Supino Declinado com Barra': 'Exercicios/Peitoral/Supino com barra declinado.gif',
  'Supino Declinado com Halteres': 'Exercicios/Peitoral/Supino Declinado com Halteres.gif',
  'Supino Fechado': 'Exercicios/Tríceps/Supino Fechado.gif',
  'Supino Inclinado com Barra': 'Exercicios/Peitoral/Supino inclinado com barra.gif',
  'Supino Inclinado com Halteres': 'Exercicios/Peitoral/Supino Inclinado com Halteres.gif',
  'Supino Inclinado na Máquina': 'Exercicios/Peitoral/Supino inclinado na máquina.gif',
  'Supino Reto': 'Exercicios/Peitoral/Supino Reto.gif',
  'Supino Reto com Halteres': 'Exercicios/Peitoral/Supino com Halteres.gif',
  'Supino Reto na Máquina': 'Exercicios/Peitoral/Supino Reto na Máquina.gif',
  'Swing Lateral com Elástico': 'Exercicios/Funcional e HIT/Elevação Lateral de Perna com Faixa Elástica.gif',
  'Tempo Push-Up (Flexão Lenta)': 'Exercicios/Calistenia/Flexão.gif',
  'Terra Sumo': 'Exercicios/Pernas/Levantamento Terra Sumô.gif',
  'Thruster (Agachamento + Press)': 'Exercicios/Crossfit/Agachamento e press com kettlebell.gif',
  'Tríceps Barra V na Polia': 'Exercicios/Tríceps/Tríceps Pulley barra V.gif',
  'Tríceps Coice com Haltere': 'Exercicios/Tríceps/Tríceps Coice com Halteres.gif',
  'Tríceps Coice na Polia': 'Exercicios/Tríceps/Tríceps Coice com Cabo.gif',
  'Tríceps Corda (Pushdown)': 'Exercicios/Tríceps/Tríceps pulley corda.gif',
  'Tríceps Francês Unilateral na Polia': 'Exercicios/Tríceps/Tríceps francês unilateral no cabo.gif',
  'Tríceps Francês com Barra W Sentado': 'Exercicios/Tríceps/Tríceps francês com barra W acima da cabeça sentado.gif',
  'Tríceps Francês com Barra W em Pé': 'Exercicios/Tríceps/Extensão de tríceps com barra atrás da cabeça.gif',
  'Tríceps Francês com Haltere': 'Exercicios/Tríceps/Tríceps Francês com Halteres.gif',
  'Tríceps Francês na Polia Baixa': 'Exercicios/Tríceps/Tríceps francês na polia com corda.gif',
  'Tríceps Inverso na Polia': 'Exercicios/Tríceps/Tríceps pulley pegada invertida.gif',
  'Tríceps Máquina': 'Exercicios/Tríceps/Extensão de tríceps na máquina.gif',
  'Tríceps Pulley (Pushdown)': 'Exercicios/Tríceps/Tríceps pulley barra.gif',
  'Tríceps Testa (Skull Crusher)': 'Exercicios/Tríceps/Tríceps testa com barra.gif',
  'Tríceps Testa com Barra W': 'Exercicios/Tríceps/Extensão de Tríceps deitado com Barra W Pegada Fechada atrás da Cabeça.gif',
  'Tríceps Testa com Halteres': 'Exercicios/Tríceps/Tríceps Testa com Banco Declinado com Halteres.gif',
  'Tríceps Unilateral na Polia': 'Exercicios/Tríceps/Extensão de tríceps lateral com cabo.gif',
  'Tríceps com Elástico': 'Exercicios/Funcional e HIT/Extensão de Tríceps com Faixa Elástica.gif',
  'Tuck Jump': 'Exercicios/Funcional e HIT/Salto com Joelhos Flexionados.gif',
  'Twist Russo': 'Exercicios/Mobilidade/Torção Oblíqua Sentada.gif',
  'Wall Sit (Cadeira na Parede)': 'Exercicios/Funcional e HIT/Wall Sit.gif',
};

/** Slug estável do nome → mesmo algoritmo no script de espelhamento e no seed. */
export function gifDoTreinoSlug(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Chave (key) do objeto no bucket público de mídia. */
export function gifDoTreinoKey(name: string): string {
  return `exercise-gifs/${gifDoTreinoSlug(name)}.gif`;
}

/**
 * URL pública final do GIF, ou null se o exercício não tem match no gifdotreino
 * ou se EXERCISE_MEDIA_BASE_URL não está configurada (→ cai no free-exercise-db).
 */
export function gifDoTreinoUrl(name: string): string | null {
  if (!GIF_DO_TREINO_SOURCE[name]) return null;
  const base = (process.env.EXERCISE_MEDIA_BASE_URL || '').replace(/\/+$/, '');
  if (!base) return null;
  return `${base}/${gifDoTreinoKey(name)}`;
}
